//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13", IsNullable=false)]
public partial class Document {
    
    private CorporateActionInstructionStatusAdvice002V13 corpActnInstrStsAdvcField;
    
    /// <remarks/>
    public CorporateActionInstructionStatusAdvice002V13 CorpActnInstrStsAdvc {
        get {
            return this.corpActnInstrStsAdvcField;
        }
        set {
            this.corpActnInstrStsAdvcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class CorporateActionInstructionStatusAdvice002V13 {
    
    private DocumentIdentification17 instrIdField;
    
    private DocumentIdentification34[] othrDocIdField;
    
    private CorporateActionGeneralInformation158 corpActnGnlInfField;
    
    private InstructionProcessingStatus49Choice[] instrPrcgStsField;
    
    private CorporateActionOption203 corpActnInstrField;
    
    private ProtectInstruction6 prtctInstrField;
    
    private CorporateActionNarrative19 addtlInfField;
    
    private SupplementaryData1[] splmtryDataField;
    
    /// <remarks/>
    public DocumentIdentification17 InstrId {
        get {
            return this.instrIdField;
        }
        set {
            this.instrIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OthrDocId")]
    public DocumentIdentification34[] OthrDocId {
        get {
            return this.othrDocIdField;
        }
        set {
            this.othrDocIdField = value;
        }
    }
    
    /// <remarks/>
    public CorporateActionGeneralInformation158 CorpActnGnlInf {
        get {
            return this.corpActnGnlInfField;
        }
        set {
            this.corpActnGnlInfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InstrPrcgSts")]
    public InstructionProcessingStatus49Choice[] InstrPrcgSts {
        get {
            return this.instrPrcgStsField;
        }
        set {
            this.instrPrcgStsField = value;
        }
    }
    
    /// <remarks/>
    public CorporateActionOption203 CorpActnInstr {
        get {
            return this.corpActnInstrField;
        }
        set {
            this.corpActnInstrField = value;
        }
    }
    
    /// <remarks/>
    public ProtectInstruction6 PrtctInstr {
        get {
            return this.prtctInstrField;
        }
        set {
            this.prtctInstrField = value;
        }
    }
    
    /// <remarks/>
    public CorporateActionNarrative19 AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
    public SupplementaryData1[] SplmtryData {
        get {
            return this.splmtryDataField;
        }
        set {
            this.splmtryDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class DocumentIdentification17 {
    
    private string idField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class SupplementaryData1 {
    
    private string plcAndNmField;
    
    private System.Xml.XmlElement envlpField;
    
    /// <remarks/>
    public string PlcAndNm {
        get {
            return this.plcAndNmField;
        }
        set {
            this.plcAndNmField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Envlp {
        get {
            return this.envlpField;
        }
        set {
            this.envlpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class CorporateActionNarrative19 {
    
    private string[] addtlTxtField;
    
    private string[] ptyCtctNrrtvField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlTxt")]
    public string[] AddtlTxt {
        get {
            return this.addtlTxtField;
        }
        set {
            this.addtlTxtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PtyCtctNrrtv")]
    public string[] PtyCtctNrrtv {
        get {
            return this.ptyCtctNrrtvField;
        }
        set {
            this.ptyCtctNrrtvField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class FinancialInstrumentQuantity31Choice {
    
    private decimal itemField;
    
    private ItemChoiceType7 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FaceAmt", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("Unit", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType7 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13", IncludeInSchema=false)]
public enum ItemChoiceType7 {
    
    /// <remarks/>
    FaceAmt,
    
    /// <remarks/>
    Unit,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class ProtectInstruction6 {
    
    private ProtectTransactionType2Code txTpField;
    
    private ProtectInstructionStatus3Code prtctTxStsField;
    
    private bool prtctTxStsFieldSpecified;
    
    private string txIdField;
    
    private string prtctSfkpgAcctField;
    
    private System.DateTime prtctDtField;
    
    private bool prtctDtFieldSpecified;
    
    private FinancialInstrumentQuantity31Choice ucvrdPrtctQtyField;
    
    /// <remarks/>
    public ProtectTransactionType2Code TxTp {
        get {
            return this.txTpField;
        }
        set {
            this.txTpField = value;
        }
    }
    
    /// <remarks/>
    public ProtectInstructionStatus3Code PrtctTxSts {
        get {
            return this.prtctTxStsField;
        }
        set {
            this.prtctTxStsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrtctTxStsSpecified {
        get {
            return this.prtctTxStsFieldSpecified;
        }
        set {
            this.prtctTxStsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string TxId {
        get {
            return this.txIdField;
        }
        set {
            this.txIdField = value;
        }
    }
    
    /// <remarks/>
    public string PrtctSfkpgAcct {
        get {
            return this.prtctSfkpgAcctField;
        }
        set {
            this.prtctSfkpgAcctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime PrtctDt {
        get {
            return this.prtctDtField;
        }
        set {
            this.prtctDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrtctDtSpecified {
        get {
            return this.prtctDtFieldSpecified;
        }
        set {
            this.prtctDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public FinancialInstrumentQuantity31Choice UcvrdPrtctQty {
        get {
            return this.ucvrdPrtctQtyField;
        }
        set {
            this.ucvrdPrtctQtyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum ProtectTransactionType2Code {
    
    /// <remarks/>
    PROT,
    
    /// <remarks/>
    COVP,
    
    /// <remarks/>
    COVR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum ProtectInstructionStatus3Code {
    
    /// <remarks/>
    OPEN,
    
    /// <remarks/>
    COVR,
    
    /// <remarks/>
    EXPI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class RestrictedFINActiveCurrencyAndAmount {
    
    private string ccyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class OriginalAndCurrentQuantities4 {
    
    private decimal faceAmtField;
    
    private decimal amtsdValField;
    
    /// <remarks/>
    public decimal FaceAmt {
        get {
            return this.faceAmtField;
        }
        set {
            this.faceAmtField = value;
        }
    }
    
    /// <remarks/>
    public decimal AmtsdVal {
        get {
            return this.amtsdValField;
        }
        set {
            this.amtsdValField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class Quantity54Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrgnlAndCurFace", typeof(OriginalAndCurrentQuantities4))]
    [System.Xml.Serialization.XmlElementAttribute("Qty", typeof(FinancialInstrumentQuantity36Choice))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class FinancialInstrumentQuantity36Choice {
    
    private decimal itemField;
    
    private ItemChoiceType5 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AmtsdVal", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("DgtlTknUnit", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("FaceAmt", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("Unit", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType5 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13", IncludeInSchema=false)]
public enum ItemChoiceType5 {
    
    /// <remarks/>
    AmtsdVal,
    
    /// <remarks/>
    DgtlTknUnit,
    
    /// <remarks/>
    FaceAmt,
    
    /// <remarks/>
    Unit,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class ProprietaryQuantity8 {
    
    private decimal qtyField;
    
    private string qtyTpField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public decimal Qty {
        get {
            return this.qtyField;
        }
        set {
            this.qtyField = value;
        }
    }
    
    /// <remarks/>
    public string QtyTp {
        get {
            return this.qtyTpField;
        }
        set {
            this.qtyTpField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class FinancialInstrumentQuantity33Choice {
    
    private decimal itemField;
    
    private ItemChoiceType6 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AmtsdVal", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("DgtlTknUnit", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("FaceAmt", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("Unit", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType6 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13", IncludeInSchema=false)]
public enum ItemChoiceType6 {
    
    /// <remarks/>
    AmtsdVal,
    
    /// <remarks/>
    DgtlTknUnit,
    
    /// <remarks/>
    FaceAmt,
    
    /// <remarks/>
    Unit,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class Quantity48Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PrtryQty", typeof(ProprietaryQuantity8))]
    [System.Xml.Serialization.XmlElementAttribute("Qty", typeof(FinancialInstrumentQuantity33Choice))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class SignedQuantityFormat11 {
    
    private ShortLong1Code shrtLngPosField;
    
    private Quantity48Choice qtyChcField;
    
    /// <remarks/>
    public ShortLong1Code ShrtLngPos {
        get {
            return this.shrtLngPosField;
        }
        set {
            this.shrtLngPosField = value;
        }
    }
    
    /// <remarks/>
    public Quantity48Choice QtyChc {
        get {
            return this.qtyChcField;
        }
        set {
            this.qtyChcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum ShortLong1Code {
    
    /// <remarks/>
    SHOR,
    
    /// <remarks/>
    LONG,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class ProprietaryQuantity9 {
    
    private decimal qtyField;
    
    private string qtyTpField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public decimal Qty {
        get {
            return this.qtyField;
        }
        set {
            this.qtyField = value;
        }
    }
    
    /// <remarks/>
    public string QtyTp {
        get {
            return this.qtyTpField;
        }
        set {
            this.qtyTpField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class Quantity53Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PrtryQty", typeof(ProprietaryQuantity9))]
    [System.Xml.Serialization.XmlElementAttribute("Qty", typeof(FinancialInstrumentQuantity36Choice))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class SignedQuantityFormat12 {
    
    private ShortLong1Code shrtLngPosField;
    
    private Quantity53Choice qtyChcField;
    
    /// <remarks/>
    public ShortLong1Code ShrtLngPos {
        get {
            return this.shrtLngPosField;
        }
        set {
            this.shrtLngPosField = value;
        }
    }
    
    /// <remarks/>
    public Quantity53Choice QtyChc {
        get {
            return this.qtyChcField;
        }
        set {
            this.qtyChcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class IdentificationSource4Choice {
    
    private string itemField;
    
    private ItemChoiceType4 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType4 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13", IncludeInSchema=false)]
public enum ItemChoiceType4 {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class OtherIdentification2 {
    
    private string idField;
    
    private string sfxField;
    
    private IdentificationSource4Choice tpField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Sfx {
        get {
            return this.sfxField;
        }
        set {
            this.sfxField = value;
        }
    }
    
    /// <remarks/>
    public IdentificationSource4Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class SecurityIdentification20 {
    
    private string iSINField;
    
    private OtherIdentification2[] othrIdField;
    
    private string descField;
    
    /// <remarks/>
    public string ISIN {
        get {
            return this.iSINField;
        }
        set {
            this.iSINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OthrId")]
    public OtherIdentification2[] OthrId {
        get {
            return this.othrIdField;
        }
        set {
            this.othrIdField = value;
        }
    }
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class GenericIdentification85 {
    
    private GenericIdentification47 tpField;
    
    private string idField;
    
    /// <remarks/>
    public GenericIdentification47 Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class GenericIdentification47 {
    
    private string idField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class SafekeepingPlaceTypeAndIdentification1 {
    
    private SafekeepingPlace1Code sfkpgPlcTpField;
    
    private string idField;
    
    /// <remarks/>
    public SafekeepingPlace1Code SfkpgPlcTp {
        get {
            return this.sfkpgPlcTpField;
        }
        set {
            this.sfkpgPlcTpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum SafekeepingPlace1Code {
    
    /// <remarks/>
    CUST,
    
    /// <remarks/>
    ICSD,
    
    /// <remarks/>
    NCSD,
    
    /// <remarks/>
    SHHE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class SafekeepingPlaceTypeAndText9 {
    
    private SafekeepingPlace2Code sfkpgPlcTpField;
    
    private string idField;
    
    /// <remarks/>
    public SafekeepingPlace2Code SfkpgPlcTp {
        get {
            return this.sfkpgPlcTpField;
        }
        set {
            this.sfkpgPlcTpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum SafekeepingPlace2Code {
    
    /// <remarks/>
    SHHE,
    
    /// <remarks/>
    ALLP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class SafekeepingPlaceFormat32Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ctry", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Id", typeof(SafekeepingPlaceTypeAndText9))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification85))]
    [System.Xml.Serialization.XmlElementAttribute("TpAndId", typeof(SafekeepingPlaceTypeAndIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class CashAccountIdentification6Choice {
    
    private string itemField;
    
    private ItemChoiceType3 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IBAN", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType3 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13", IncludeInSchema=false)]
public enum ItemChoiceType3 {
    
    /// <remarks/>
    IBAN,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class GenericIdentification84 {
    
    private string idField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class PartyIdentification136Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification84))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class OptionFeaturesFormat27Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(OptionFeatures12Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification47))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum OptionFeatures12Code {
    
    /// <remarks/>
    OPLF,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class CorporateActionOption42Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(CorporateActionOption17Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification47))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum CorporateActionOption17Code {
    
    /// <remarks/>
    ABST,
    
    /// <remarks/>
    BSPL,
    
    /// <remarks/>
    BUYA,
    
    /// <remarks/>
    CASE,
    
    /// <remarks/>
    CASH,
    
    /// <remarks/>
    CEXC,
    
    /// <remarks/>
    CONN,
    
    /// <remarks/>
    CONY,
    
    /// <remarks/>
    CTEN,
    
    /// <remarks/>
    EXER,
    
    /// <remarks/>
    LAPS,
    
    /// <remarks/>
    MKDW,
    
    /// <remarks/>
    MKUP,
    
    /// <remarks/>
    MPUT,
    
    /// <remarks/>
    NOAC,
    
    /// <remarks/>
    NOQU,
    
    /// <remarks/>
    OFFR,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    OVER,
    
    /// <remarks/>
    QINV,
    
    /// <remarks/>
    SECU,
    
    /// <remarks/>
    SLLE,
    
    /// <remarks/>
    TAXI,
    
    /// <remarks/>
    PRUN,
    
    /// <remarks/>
    BOBD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class OptionNumber1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(OptionNumber1Code))]
    [System.Xml.Serialization.XmlElementAttribute("Nb", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum OptionNumber1Code {
    
    /// <remarks/>
    UNSO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class CorporateActionOption203 {
    
    private OptionNumber1Choice optnNbField;
    
    private CorporateActionOption42Choice optnTpField;
    
    private OptionFeaturesFormat27Choice optnFeatrsField;
    
    private PartyIdentification136Choice acctOwnrField;
    
    private string sfkpgAcctField;
    
    private string blckChainAdrOrWlltField;
    
    private CashAccountIdentification6Choice cshAcctField;
    
    private SafekeepingPlaceFormat32Choice sfkpgPlcField;
    
    private SecurityIdentification20 finInstrmIdField;
    
    private SignedQuantityFormat12 ttlElgblBalField;
    
    private SignedQuantityFormat12 instdBalField;
    
    private SignedQuantityFormat12 uinstdBalField;
    
    private SignedQuantityFormat11 prtctBalField;
    
    private Quantity54Choice stsQtyField;
    
    private RestrictedFINActiveCurrencyAndAmount stsCshAmtField;
    
    private bool slctnDealrFeeIndField;
    
    private bool slctnDealrFeeIndFieldSpecified;
    
    /// <remarks/>
    public OptionNumber1Choice OptnNb {
        get {
            return this.optnNbField;
        }
        set {
            this.optnNbField = value;
        }
    }
    
    /// <remarks/>
    public CorporateActionOption42Choice OptnTp {
        get {
            return this.optnTpField;
        }
        set {
            this.optnTpField = value;
        }
    }
    
    /// <remarks/>
    public OptionFeaturesFormat27Choice OptnFeatrs {
        get {
            return this.optnFeatrsField;
        }
        set {
            this.optnFeatrsField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification136Choice AcctOwnr {
        get {
            return this.acctOwnrField;
        }
        set {
            this.acctOwnrField = value;
        }
    }
    
    /// <remarks/>
    public string SfkpgAcct {
        get {
            return this.sfkpgAcctField;
        }
        set {
            this.sfkpgAcctField = value;
        }
    }
    
    /// <remarks/>
    public string BlckChainAdrOrWllt {
        get {
            return this.blckChainAdrOrWlltField;
        }
        set {
            this.blckChainAdrOrWlltField = value;
        }
    }
    
    /// <remarks/>
    public CashAccountIdentification6Choice CshAcct {
        get {
            return this.cshAcctField;
        }
        set {
            this.cshAcctField = value;
        }
    }
    
    /// <remarks/>
    public SafekeepingPlaceFormat32Choice SfkpgPlc {
        get {
            return this.sfkpgPlcField;
        }
        set {
            this.sfkpgPlcField = value;
        }
    }
    
    /// <remarks/>
    public SecurityIdentification20 FinInstrmId {
        get {
            return this.finInstrmIdField;
        }
        set {
            this.finInstrmIdField = value;
        }
    }
    
    /// <remarks/>
    public SignedQuantityFormat12 TtlElgblBal {
        get {
            return this.ttlElgblBalField;
        }
        set {
            this.ttlElgblBalField = value;
        }
    }
    
    /// <remarks/>
    public SignedQuantityFormat12 InstdBal {
        get {
            return this.instdBalField;
        }
        set {
            this.instdBalField = value;
        }
    }
    
    /// <remarks/>
    public SignedQuantityFormat12 UinstdBal {
        get {
            return this.uinstdBalField;
        }
        set {
            this.uinstdBalField = value;
        }
    }
    
    /// <remarks/>
    public SignedQuantityFormat11 PrtctBal {
        get {
            return this.prtctBalField;
        }
        set {
            this.prtctBalField = value;
        }
    }
    
    /// <remarks/>
    public Quantity54Choice StsQty {
        get {
            return this.stsQtyField;
        }
        set {
            this.stsQtyField = value;
        }
    }
    
    /// <remarks/>
    public RestrictedFINActiveCurrencyAndAmount StsCshAmt {
        get {
            return this.stsCshAmtField;
        }
        set {
            this.stsCshAmtField = value;
        }
    }
    
    /// <remarks/>
    public bool SlctnDealrFeeInd {
        get {
            return this.slctnDealrFeeIndField;
        }
        set {
            this.slctnDealrFeeIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SlctnDealrFeeIndSpecified {
        get {
            return this.slctnDealrFeeIndFieldSpecified;
        }
        set {
            this.slctnDealrFeeIndFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class ProprietaryReason5 {
    
    private GenericIdentification47 rsnField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public GenericIdentification47 Rsn {
        get {
            return this.rsnField;
        }
        set {
            this.rsnField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class ProprietaryStatusAndReason7 {
    
    private GenericIdentification47 prtryStsField;
    
    private ProprietaryReason5[] prtryRsnField;
    
    /// <remarks/>
    public GenericIdentification47 PrtrySts {
        get {
            return this.prtryStsField;
        }
        set {
            this.prtryStsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PrtryRsn")]
    public ProprietaryReason5[] PrtryRsn {
        get {
            return this.prtryRsnField;
        }
        set {
            this.prtryRsnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class NoSpecifiedReason1 {
    
    private NoReasonCode noSpcfdRsnField;
    
    /// <remarks/>
    public NoReasonCode NoSpcfdRsn {
        get {
            return this.noSpcfdRsnField;
        }
        set {
            this.noSpcfdRsnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum NoReasonCode {
    
    /// <remarks/>
    NORE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class PendingReason64Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(PendingReason23Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification47))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum PendingReason23Code {
    
    /// <remarks/>
    ADEA,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    FULL,
    
    /// <remarks/>
    MCER,
    
    /// <remarks/>
    MONY,
    
    /// <remarks/>
    LACK,
    
    /// <remarks/>
    LATE,
    
    /// <remarks/>
    DQUA,
    
    /// <remarks/>
    PENR,
    
    /// <remarks/>
    CERT,
    
    /// <remarks/>
    DQCS,
    
    /// <remarks/>
    ITAX,
    
    /// <remarks/>
    NTAX,
    
    /// <remarks/>
    MTAX,
    
    /// <remarks/>
    SNAV,
    
    /// <remarks/>
    BSTR,
    
    /// <remarks/>
    IPAW,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class PendingStatusReason25 {
    
    private PendingReason64Choice rsnCdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public PendingReason64Choice RsnCd {
        get {
            return this.rsnCdField;
        }
        set {
            this.rsnCdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class PendingStatus68Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(PendingStatusReason25))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class RejectedReason46Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(RejectionReason66Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification47))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum RejectionReason66Code {
    
    /// <remarks/>
    ADEA,
    
    /// <remarks/>
    CERT,
    
    /// <remarks/>
    INVA,
    
    /// <remarks/>
    OPTY,
    
    /// <remarks/>
    ULNK,
    
    /// <remarks/>
    DSEC,
    
    /// <remarks/>
    LACK,
    
    /// <remarks/>
    LATE,
    
    /// <remarks/>
    NMTY,
    
    /// <remarks/>
    FULL,
    
    /// <remarks/>
    CANC,
    
    /// <remarks/>
    INTV,
    
    /// <remarks/>
    OPNM,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    DQUA,
    
    /// <remarks/>
    REFT,
    
    /// <remarks/>
    SAFE,
    
    /// <remarks/>
    EVNM,
    
    /// <remarks/>
    DQCS,
    
    /// <remarks/>
    DQCC,
    
    /// <remarks/>
    DQAM,
    
    /// <remarks/>
    IRDQ,
    
    /// <remarks/>
    DQBV,
    
    /// <remarks/>
    DQBI,
    
    /// <remarks/>
    SHAR,
    
    /// <remarks/>
    ITAX,
    
    /// <remarks/>
    NTAX,
    
    /// <remarks/>
    MTAX,
    
    /// <remarks/>
    ISOL,
    
    /// <remarks/>
    BSTR,
    
    /// <remarks/>
    CTCT,
    
    /// <remarks/>
    DUPL,
    
    /// <remarks/>
    PROI,
    
    /// <remarks/>
    PRON,
    
    /// <remarks/>
    PROT,
    
    /// <remarks/>
    TRTI,
    
    /// <remarks/>
    IPAW,
    
    /// <remarks/>
    REJA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class RejectedStatusReason44 {
    
    private RejectedReason46Choice rsnCdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public RejectedReason46Choice RsnCd {
        get {
            return this.rsnCdField;
        }
        set {
            this.rsnCdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class RejectedStatus46Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(RejectedStatusReason44))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class AcceptedReason11Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(AcknowledgementReason7Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification47))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum AcknowledgementReason7Code {
    
    /// <remarks/>
    NSTP,
    
    /// <remarks/>
    OTHR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class AcceptedStatusReason10 {
    
    private AcceptedReason11Choice rsnCdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public AcceptedReason11Choice RsnCd {
        get {
            return this.rsnCdField;
        }
        set {
            this.rsnCdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class AcceptedStatus9Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(AcceptedStatusReason10))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class CancelledReason11Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(CancelledStatusReason6Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification47))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum CancelledStatusReason6Code {
    
    /// <remarks/>
    CANI,
    
    /// <remarks/>
    CANO,
    
    /// <remarks/>
    CANS,
    
    /// <remarks/>
    CSUB,
    
    /// <remarks/>
    OTHR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class CancelledStatusReason14 {
    
    private CancelledReason11Choice rsnCdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public CancelledReason11Choice RsnCd {
        get {
            return this.rsnCdField;
        }
        set {
            this.rsnCdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class CancelledStatus15Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(CancelledStatusReason14))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class InstructionProcessingStatus49Choice {
    
    private object itemField;
    
    private ItemChoiceType2 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AccptdForFrthrPrcg", typeof(AcceptedStatus9Choice))]
    [System.Xml.Serialization.XmlElementAttribute("Canc", typeof(CancelledStatus15Choice))]
    [System.Xml.Serialization.XmlElementAttribute("DfltActn", typeof(NoSpecifiedReason1))]
    [System.Xml.Serialization.XmlElementAttribute("Pdg", typeof(PendingStatus68Choice))]
    [System.Xml.Serialization.XmlElementAttribute("PrtrySts", typeof(ProprietaryStatusAndReason7))]
    [System.Xml.Serialization.XmlElementAttribute("Rjctd", typeof(RejectedStatus46Choice))]
    [System.Xml.Serialization.XmlElementAttribute("StgInstr", typeof(NoSpecifiedReason1))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType2 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13", IncludeInSchema=false)]
public enum ItemChoiceType2 {
    
    /// <remarks/>
    AccptdForFrthrPrcg,
    
    /// <remarks/>
    Canc,
    
    /// <remarks/>
    DfltActn,
    
    /// <remarks/>
    Pdg,
    
    /// <remarks/>
    PrtrySts,
    
    /// <remarks/>
    Rjctd,
    
    /// <remarks/>
    StgInstr,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class CorporateActionEventType103Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(CorporateActionEventType34Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification47))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public enum CorporateActionEventType34Code {
    
    /// <remarks/>
    ACTV,
    
    /// <remarks/>
    ATTI,
    
    /// <remarks/>
    BRUP,
    
    /// <remarks/>
    DFLT,
    
    /// <remarks/>
    BONU,
    
    /// <remarks/>
    EXRI,
    
    /// <remarks/>
    CAPD,
    
    /// <remarks/>
    CAPG,
    
    /// <remarks/>
    CAPI,
    
    /// <remarks/>
    DRCA,
    
    /// <remarks/>
    DVCA,
    
    /// <remarks/>
    CHAN,
    
    /// <remarks/>
    COOP,
    
    /// <remarks/>
    CLSA,
    
    /// <remarks/>
    CONS,
    
    /// <remarks/>
    CONV,
    
    /// <remarks/>
    CREV,
    
    /// <remarks/>
    DECR,
    
    /// <remarks/>
    DETI,
    
    /// <remarks/>
    DSCL,
    
    /// <remarks/>
    DVOP,
    
    /// <remarks/>
    DRIP,
    
    /// <remarks/>
    DRAW,
    
    /// <remarks/>
    DTCH,
    
    /// <remarks/>
    EXOF,
    
    /// <remarks/>
    REDM,
    
    /// <remarks/>
    MCAL,
    
    /// <remarks/>
    INCR,
    
    /// <remarks/>
    PPMT,
    
    /// <remarks/>
    INTR,
    
    /// <remarks/>
    RHDI,
    
    /// <remarks/>
    LIQU,
    
    /// <remarks/>
    EXTM,
    
    /// <remarks/>
    MRGR,
    
    /// <remarks/>
    NOOF,
    
    /// <remarks/>
    CERT,
    
    /// <remarks/>
    ODLT,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    PARI,
    
    /// <remarks/>
    PCAL,
    
    /// <remarks/>
    PRED,
    
    /// <remarks/>
    PINK,
    
    /// <remarks/>
    PLAC,
    
    /// <remarks/>
    PDEF,
    
    /// <remarks/>
    PRIO,
    
    /// <remarks/>
    BPUT,
    
    /// <remarks/>
    REDO,
    
    /// <remarks/>
    REMK,
    
    /// <remarks/>
    BIDS,
    
    /// <remarks/>
    SPLR,
    
    /// <remarks/>
    RHTS,
    
    /// <remarks/>
    DVSC,
    
    /// <remarks/>
    SHPR,
    
    /// <remarks/>
    SMAL,
    
    /// <remarks/>
    SOFF,
    
    /// <remarks/>
    DVSE,
    
    /// <remarks/>
    SPLF,
    
    /// <remarks/>
    TREC,
    
    /// <remarks/>
    TEND,
    
    /// <remarks/>
    DLST,
    
    /// <remarks/>
    SUSP,
    
    /// <remarks/>
    EXWA,
    
    /// <remarks/>
    WTRC,
    
    /// <remarks/>
    WRTH,
    
    /// <remarks/>
    ACCU,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class CorporateActionGeneralInformation158 {
    
    private string corpActnEvtIdField;
    
    private string offclCorpActnEvtIdField;
    
    private string clssActnNbField;
    
    private CorporateActionEventType103Choice evtTpField;
    
    /// <remarks/>
    public string CorpActnEvtId {
        get {
            return this.corpActnEvtIdField;
        }
        set {
            this.corpActnEvtIdField = value;
        }
    }
    
    /// <remarks/>
    public string OffclCorpActnEvtId {
        get {
            return this.offclCorpActnEvtIdField;
        }
        set {
            this.offclCorpActnEvtIdField = value;
        }
    }
    
    /// <remarks/>
    public string ClssActnNb {
        get {
            return this.clssActnNbField;
        }
        set {
            this.clssActnNbField = value;
        }
    }
    
    /// <remarks/>
    public CorporateActionEventType103Choice EvtTp {
        get {
            return this.evtTpField;
        }
        set {
            this.evtTpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class GenericIdentification86 {
    
    private string idField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class DocumentNumber6Choice {
    
    private object itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LngNb", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PrtryNb", typeof(GenericIdentification86))]
    [System.Xml.Serialization.XmlElementAttribute("ShrtNb", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13", IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    LngNb,
    
    /// <remarks/>
    PrtryNb,
    
    /// <remarks/>
    ShrtNb,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class DocumentIdentification4Choice {
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AcctOwnrDocId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("AcctSvcrDocId", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    AcctOwnrDocId,
    
    /// <remarks/>
    AcctSvcrDocId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.034.002.13")]
public partial class DocumentIdentification34 {
    
    private DocumentIdentification4Choice idField;
    
    private DocumentNumber6Choice docNbField;
    
    /// <remarks/>
    public DocumentIdentification4Choice Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public DocumentNumber6Choice DocNb {
        get {
            return this.docNbField;
        }
        set {
            this.docNbField = value;
        }
    }
}
