//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02", IsNullable=false)]
public partial class Document {
    
    private FraudDispositionInitiationV02 frdDspstnInitnField;
    
    /// <remarks/>
    public FraudDispositionInitiationV02 FrdDspstnInitn {
        get {
            return this.frdDspstnInitnField;
        }
        set {
            this.frdDspstnInitnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class FraudDispositionInitiationV02 {
    
    private Header66 hdrField;
    
    private FraudDispositionInitiation2 bodyField;
    
    private ContentInformationType20 sctyTrlrField;
    
    /// <remarks/>
    public Header66 Hdr {
        get {
            return this.hdrField;
        }
        set {
            this.hdrField = value;
        }
    }
    
    /// <remarks/>
    public FraudDispositionInitiation2 Body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    public ContentInformationType20 SctyTrlr {
        get {
            return this.sctyTrlrField;
        }
        set {
            this.sctyTrlrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Header66 {
    
    private MessageFunction29Code msgFctnField;
    
    private string prtcolVrsnField;
    
    private string xchgIdField;
    
    private string reTrnsmssnCntrField;
    
    private System.DateTime creDtTmField;
    
    private BatchManagementInformation1 btchMgmtInfField;
    
    private GenericIdentification183 initgPtyField;
    
    private GenericIdentification183 rcptPtyField;
    
    private AdditionalData1[] tracDataField;
    
    private Traceability9[] tracbltField;
    
    /// <remarks/>
    public MessageFunction29Code MsgFctn {
        get {
            return this.msgFctnField;
        }
        set {
            this.msgFctnField = value;
        }
    }
    
    /// <remarks/>
    public string PrtcolVrsn {
        get {
            return this.prtcolVrsnField;
        }
        set {
            this.prtcolVrsnField = value;
        }
    }
    
    /// <remarks/>
    public string XchgId {
        get {
            return this.xchgIdField;
        }
        set {
            this.xchgIdField = value;
        }
    }
    
    /// <remarks/>
    public string ReTrnsmssnCntr {
        get {
            return this.reTrnsmssnCntrField;
        }
        set {
            this.reTrnsmssnCntrField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
    
    /// <remarks/>
    public BatchManagementInformation1 BtchMgmtInf {
        get {
            return this.btchMgmtInfField;
        }
        set {
            this.btchMgmtInfField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification183 InitgPty {
        get {
            return this.initgPtyField;
        }
        set {
            this.initgPtyField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification183 RcptPty {
        get {
            return this.rcptPtyField;
        }
        set {
            this.rcptPtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TracData")]
    public AdditionalData1[] TracData {
        get {
            return this.tracDataField;
        }
        set {
            this.tracDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tracblt")]
    public Traceability9[] Tracblt {
        get {
            return this.tracbltField;
        }
        set {
            this.tracbltField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum MessageFunction29Code {
    
    /// <remarks/>
    ADVC,
    
    /// <remarks/>
    NOTI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class BatchManagementInformation1 {
    
    private string colltnIdField;
    
    private string btchIdField;
    
    private string msgSeqNbField;
    
    private byte[] msgChcksmInptValField;
    
    /// <remarks/>
    public string ColltnId {
        get {
            return this.colltnIdField;
        }
        set {
            this.colltnIdField = value;
        }
    }
    
    /// <remarks/>
    public string BtchId {
        get {
            return this.btchIdField;
        }
        set {
            this.btchIdField = value;
        }
    }
    
    /// <remarks/>
    public string MsgSeqNb {
        get {
            return this.msgSeqNbField;
        }
        set {
            this.msgSeqNbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] MsgChcksmInptVal {
        get {
            return this.msgChcksmInptValField;
        }
        set {
            this.msgChcksmInptValField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class MACData1 {
    
    private string ctrlField;
    
    private string keySetIdrField;
    
    private string drvdInfField;
    
    private string algoField;
    
    private string keyLngthField;
    
    private string keyPrtcnField;
    
    private string keyIndxField;
    
    private string pddgMtdField;
    
    private string initlstnVctrField;
    
    /// <remarks/>
    public string Ctrl {
        get {
            return this.ctrlField;
        }
        set {
            this.ctrlField = value;
        }
    }
    
    /// <remarks/>
    public string KeySetIdr {
        get {
            return this.keySetIdrField;
        }
        set {
            this.keySetIdrField = value;
        }
    }
    
    /// <remarks/>
    public string DrvdInf {
        get {
            return this.drvdInfField;
        }
        set {
            this.drvdInfField = value;
        }
    }
    
    /// <remarks/>
    public string Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public string KeyLngth {
        get {
            return this.keyLngthField;
        }
        set {
            this.keyLngthField = value;
        }
    }
    
    /// <remarks/>
    public string KeyPrtcn {
        get {
            return this.keyPrtcnField;
        }
        set {
            this.keyPrtcnField = value;
        }
    }
    
    /// <remarks/>
    public string KeyIndx {
        get {
            return this.keyIndxField;
        }
        set {
            this.keyIndxField = value;
        }
    }
    
    /// <remarks/>
    public string PddgMtd {
        get {
            return this.pddgMtdField;
        }
        set {
            this.pddgMtdField = value;
        }
    }
    
    /// <remarks/>
    public string InitlstnVctr {
        get {
            return this.initlstnVctrField;
        }
        set {
            this.initlstnVctrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class ContentInformationType20 {
    
    private MACData1 mACDataField;
    
    private string mACField;
    
    /// <remarks/>
    public MACData1 MACData {
        get {
            return this.mACDataField;
        }
        set {
            this.mACDataField = value;
        }
    }
    
    /// <remarks/>
    public string MAC {
        get {
            return this.mACField;
        }
        set {
            this.mACField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class SupplementaryData1 {
    
    private string plcAndNmField;
    
    private System.Xml.XmlElement envlpField;
    
    /// <remarks/>
    public string PlcAndNm {
        get {
            return this.plcAndNmField;
        }
        set {
            this.plcAndNmField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Envlp {
        get {
            return this.envlpField;
        }
        set {
            this.envlpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class FraudDispositionStatus2 {
    
    private ActionTaken1Code actnTakenField;
    
    private string othrActnTakenField;
    
    private string[] errDataField;
    
    private string[] wrngDataField;
    
    private AdditionalInformation30[] addtlInfField;
    
    /// <remarks/>
    public ActionTaken1Code ActnTaken {
        get {
            return this.actnTakenField;
        }
        set {
            this.actnTakenField = value;
        }
    }
    
    /// <remarks/>
    public string OthrActnTaken {
        get {
            return this.othrActnTakenField;
        }
        set {
            this.othrActnTakenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ErrData")]
    public string[] ErrData {
        get {
            return this.errDataField;
        }
        set {
            this.errDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("WrngData")]
    public string[] WrngData {
        get {
            return this.wrngDataField;
        }
        set {
            this.wrngDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlInf")]
    public AdditionalInformation30[] AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum ActionTaken1Code {
    
    /// <remarks/>
    ACCP,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    RJCT,
    
    /// <remarks/>
    WARN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class AdditionalInformation30 {
    
    private PartyType19Code rcptField;
    
    private bool rcptFieldSpecified;
    
    private UserInterface8Code[] trgtField;
    
    private OutputFormat4Code frmtField;
    
    private bool frmtFieldSpecified;
    
    private string tpField;
    
    private string langField;
    
    private string valField;
    
    /// <remarks/>
    public PartyType19Code Rcpt {
        get {
            return this.rcptField;
        }
        set {
            this.rcptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RcptSpecified {
        get {
            return this.rcptFieldSpecified;
        }
        set {
            this.rcptFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Trgt")]
    public UserInterface8Code[] Trgt {
        get {
            return this.trgtField;
        }
        set {
            this.trgtField = value;
        }
    }
    
    /// <remarks/>
    public OutputFormat4Code Frmt {
        get {
            return this.frmtField;
        }
        set {
            this.frmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FrmtSpecified {
        get {
            return this.frmtFieldSpecified;
        }
        set {
            this.frmtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    public string Val {
        get {
            return this.valField;
        }
        set {
            this.valField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum PartyType19Code {
    
    /// <remarks/>
    ACCP,
    
    /// <remarks/>
    ACQR,
    
    /// <remarks/>
    ACQP,
    
    /// <remarks/>
    CISS,
    
    /// <remarks/>
    CISP,
    
    /// <remarks/>
    AGNT,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum UserInterface8Code {
    
    /// <remarks/>
    DSPU,
    
    /// <remarks/>
    FILE,
    
    /// <remarks/>
    LOGF,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    OTHN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum OutputFormat4Code {
    
    /// <remarks/>
    FLNM,
    
    /// <remarks/>
    MREF,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    SMSI,
    
    /// <remarks/>
    TEXT,
    
    /// <remarks/>
    URLI,
    
    /// <remarks/>
    HTML,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class FeeAmount3 {
    
    private decimal amtField;
    
    private CreditDebit3Code cdtDbtField;
    
    private bool cdtDbtFieldSpecified;
    
    private string ccyField;
    
    private decimal fctvXchgRateField;
    
    private bool fctvXchgRateFieldSpecified;
    
    private System.DateTime convsDtField;
    
    private bool convsDtFieldSpecified;
    
    private System.DateTime convsTmField;
    
    private bool convsTmFieldSpecified;
    
    /// <remarks/>
    public decimal Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <remarks/>
    public CreditDebit3Code CdtDbt {
        get {
            return this.cdtDbtField;
        }
        set {
            this.cdtDbtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CdtDbtSpecified {
        get {
            return this.cdtDbtFieldSpecified;
        }
        set {
            this.cdtDbtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    public decimal FctvXchgRate {
        get {
            return this.fctvXchgRateField;
        }
        set {
            this.fctvXchgRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FctvXchgRateSpecified {
        get {
            return this.fctvXchgRateFieldSpecified;
        }
        set {
            this.fctvXchgRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ConvsDt {
        get {
            return this.convsDtField;
        }
        set {
            this.convsDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConvsDtSpecified {
        get {
            return this.convsDtFieldSpecified;
        }
        set {
            this.convsDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime ConvsTm {
        get {
            return this.convsTmField;
        }
        set {
            this.convsTmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConvsTmSpecified {
        get {
            return this.convsTmFieldSpecified;
        }
        set {
            this.convsTmFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum CreditDebit3Code {
    
    /// <remarks/>
    CRDT,
    
    /// <remarks/>
    DBIT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class AdditionalFee2 {
    
    private TypeOfAmount21Code tpField;
    
    private string othrTpField;
    
    private string feePrgmField;
    
    private string feeDscrptrField;
    
    private FeeAmount3 feeAmtField;
    
    private FeeAmount3 feeRcncltnAmtField;
    
    private string descField;
    
    private AdditionalData1[] addtlDataField;
    
    /// <remarks/>
    public TypeOfAmount21Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string OthrTp {
        get {
            return this.othrTpField;
        }
        set {
            this.othrTpField = value;
        }
    }
    
    /// <remarks/>
    public string FeePrgm {
        get {
            return this.feePrgmField;
        }
        set {
            this.feePrgmField = value;
        }
    }
    
    /// <remarks/>
    public string FeeDscrptr {
        get {
            return this.feeDscrptrField;
        }
        set {
            this.feeDscrptrField = value;
        }
    }
    
    /// <remarks/>
    public FeeAmount3 FeeAmt {
        get {
            return this.feeAmtField;
        }
        set {
            this.feeAmtField = value;
        }
    }
    
    /// <remarks/>
    public FeeAmount3 FeeRcncltnAmt {
        get {
            return this.feeRcncltnAmtField;
        }
        set {
            this.feeRcncltnAmtField = value;
        }
    }
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlData")]
    public AdditionalData1[] AddtlData {
        get {
            return this.addtlDataField;
        }
        set {
            this.addtlDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum TypeOfAmount21Code {
    
    /// <remarks/>
    INTC,
    
    /// <remarks/>
    FEEP,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    FEEA,
    
    /// <remarks/>
    CSIF,
    
    /// <remarks/>
    MXIF,
    
    /// <remarks/>
    MNIF,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class AdditionalData1 {
    
    private string tpField;
    
    private string valField;
    
    /// <remarks/>
    public string Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Val {
        get {
            return this.valField;
        }
        set {
            this.valField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class ReportedFraud2 {
    
    private FraudType1Code frdTpField;
    
    private string othrFrdTpField;
    
    private FraudReportingAction1Code frdRptgActnField;
    
    private string othrFrdRptgActnField;
    
    private PartyType25Code rptgNttyField;
    
    private string othrRptgNttyField;
    
    private string submitrCaseRefField;
    
    private string caseRefField;
    
    /// <remarks/>
    public FraudType1Code FrdTp {
        get {
            return this.frdTpField;
        }
        set {
            this.frdTpField = value;
        }
    }
    
    /// <remarks/>
    public string OthrFrdTp {
        get {
            return this.othrFrdTpField;
        }
        set {
            this.othrFrdTpField = value;
        }
    }
    
    /// <remarks/>
    public FraudReportingAction1Code FrdRptgActn {
        get {
            return this.frdRptgActnField;
        }
        set {
            this.frdRptgActnField = value;
        }
    }
    
    /// <remarks/>
    public string OthrFrdRptgActn {
        get {
            return this.othrFrdRptgActnField;
        }
        set {
            this.othrFrdRptgActnField = value;
        }
    }
    
    /// <remarks/>
    public PartyType25Code RptgNtty {
        get {
            return this.rptgNttyField;
        }
        set {
            this.rptgNttyField = value;
        }
    }
    
    /// <remarks/>
    public string OthrRptgNtty {
        get {
            return this.othrRptgNttyField;
        }
        set {
            this.othrRptgNttyField = value;
        }
    }
    
    /// <remarks/>
    public string SubmitrCaseRef {
        get {
            return this.submitrCaseRefField;
        }
        set {
            this.submitrCaseRefField = value;
        }
    }
    
    /// <remarks/>
    public string CaseRef {
        get {
            return this.caseRefField;
        }
        set {
            this.caseRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum FraudType1Code {
    
    /// <remarks/>
    ACTO,
    
    /// <remarks/>
    CWUI,
    
    /// <remarks/>
    CRNT,
    
    /// <remarks/>
    FRAC,
    
    /// <remarks/>
    FRAP,
    
    /// <remarks/>
    CWKA,
    
    /// <remarks/>
    CRDL,
    
    /// <remarks/>
    MISC,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    CRDS,
    
    /// <remarks/>
    CNPA,
    
    /// <remarks/>
    MUFD,
    
    /// <remarks/>
    COSN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum FraudReportingAction1Code {
    
    /// <remarks/>
    DUPL,
    
    /// <remarks/>
    CLSE,
    
    /// <remarks/>
    NEWF,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    REOP,
    
    /// <remarks/>
    UPDT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum PartyType25Code {
    
    /// <remarks/>
    ACQR,
    
    /// <remarks/>
    CISS,
    
    /// <remarks/>
    CSCH,
    
    /// <remarks/>
    AGNT,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Transaction128 {
    
    private string frdTxIdField;
    
    private ReportedFraud2 rptdFrdField;
    
    private AdditionalFee2[] addtlFeeField;
    
    private AdditionalInformation30[] addtlInfField;
    
    private AdditionalData1[] addtlDataField;
    
    /// <remarks/>
    public string FrdTxId {
        get {
            return this.frdTxIdField;
        }
        set {
            this.frdTxIdField = value;
        }
    }
    
    /// <remarks/>
    public ReportedFraud2 RptdFrd {
        get {
            return this.rptdFrdField;
        }
        set {
            this.rptdFrdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlFee")]
    public AdditionalFee2[] AddtlFee {
        get {
            return this.addtlFeeField;
        }
        set {
            this.addtlFeeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlInf")]
    public AdditionalInformation30[] AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlData")]
    public AdditionalData1[] AddtlData {
        get {
            return this.addtlDataField;
        }
        set {
            this.addtlDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Reconciliation3 {
    
    private string idField;
    
    private System.DateTime dtField;
    
    private bool dtFieldSpecified;
    
    private string chckptRefField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Dt {
        get {
            return this.dtField;
        }
        set {
            this.dtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DtSpecified {
        get {
            return this.dtFieldSpecified;
        }
        set {
            this.dtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ChckptRef {
        get {
            return this.chckptRefField;
        }
        set {
            this.chckptRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class SettlementReportingEntity1 {
    
    private string tpField;
    
    private string idField;
    
    /// <remarks/>
    public string Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class SettlementServiceDate2 {
    
    private System.DateTime reqdSttlmDtField;
    
    private bool reqdSttlmDtFieldSpecified;
    
    private bool dfrrdSttlmIndField;
    
    private bool dfrrdSttlmIndFieldSpecified;
    
    private System.DateTime sttlmDtField;
    
    private bool sttlmDtFieldSpecified;
    
    private System.DateTime sttlmTmField;
    
    private bool sttlmTmFieldSpecified;
    
    private string sttlmPrdField;
    
    private System.DateTime sttlmCutOffTmField;
    
    private bool sttlmCutOffTmFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ReqdSttlmDt {
        get {
            return this.reqdSttlmDtField;
        }
        set {
            this.reqdSttlmDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReqdSttlmDtSpecified {
        get {
            return this.reqdSttlmDtFieldSpecified;
        }
        set {
            this.reqdSttlmDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool DfrrdSttlmInd {
        get {
            return this.dfrrdSttlmIndField;
        }
        set {
            this.dfrrdSttlmIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DfrrdSttlmIndSpecified {
        get {
            return this.dfrrdSttlmIndFieldSpecified;
        }
        set {
            this.dfrrdSttlmIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime SttlmDt {
        get {
            return this.sttlmDtField;
        }
        set {
            this.sttlmDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SttlmDtSpecified {
        get {
            return this.sttlmDtFieldSpecified;
        }
        set {
            this.sttlmDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime SttlmTm {
        get {
            return this.sttlmTmField;
        }
        set {
            this.sttlmTmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SttlmTmSpecified {
        get {
            return this.sttlmTmFieldSpecified;
        }
        set {
            this.sttlmTmFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string SttlmPrd {
        get {
            return this.sttlmPrdField;
        }
        set {
            this.sttlmPrdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime SttlmCutOffTm {
        get {
            return this.sttlmCutOffTmField;
        }
        set {
            this.sttlmCutOffTmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SttlmCutOffTmSpecified {
        get {
            return this.sttlmCutOffTmFieldSpecified;
        }
        set {
            this.sttlmCutOffTmFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class SettlementServiceMode1 {
    
    private string tpField;
    
    private string idField;
    
    private string shrtNmField;
    
    private Priority3Code sttlmPrtyField;
    
    private bool sttlmPrtyFieldSpecified;
    
    /// <remarks/>
    public string Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string ShrtNm {
        get {
            return this.shrtNmField;
        }
        set {
            this.shrtNmField = value;
        }
    }
    
    /// <remarks/>
    public Priority3Code SttlmPrty {
        get {
            return this.sttlmPrtyField;
        }
        set {
            this.sttlmPrtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SttlmPrtySpecified {
        get {
            return this.sttlmPrtyFieldSpecified;
        }
        set {
            this.sttlmPrtyFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum Priority3Code {
    
    /// <remarks/>
    URGT,
    
    /// <remarks/>
    HIGH,
    
    /// <remarks/>
    NORM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class SettlementService4 {
    
    private SettlementServiceMode1 sttlmSvcApldField;
    
    private SettlementServiceDate2 sttlmSvcDtsField;
    
    private SettlementReportingEntity1 sttlmRptgNttyField;
    
    private AdditionalData1[] addtlSttlmInfField;
    
    /// <remarks/>
    public SettlementServiceMode1 SttlmSvcApld {
        get {
            return this.sttlmSvcApldField;
        }
        set {
            this.sttlmSvcApldField = value;
        }
    }
    
    /// <remarks/>
    public SettlementServiceDate2 SttlmSvcDts {
        get {
            return this.sttlmSvcDtsField;
        }
        set {
            this.sttlmSvcDtsField = value;
        }
    }
    
    /// <remarks/>
    public SettlementReportingEntity1 SttlmRptgNtty {
        get {
            return this.sttlmRptgNttyField;
        }
        set {
            this.sttlmRptgNttyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlSttlmInf")]
    public AdditionalData1[] AddtlSttlmInf {
        get {
            return this.addtlSttlmInfField;
        }
        set {
            this.addtlSttlmInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Jurisdiction2 {
    
    private bool dmstIndField;
    
    private bool dmstIndFieldSpecified;
    
    private string dmstQlfctnField;
    
    /// <remarks/>
    public bool DmstInd {
        get {
            return this.dmstIndField;
        }
        set {
            this.dmstIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DmstIndSpecified {
        get {
            return this.dmstIndFieldSpecified;
        }
        set {
            this.dmstIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string DmstQlfctn {
        get {
            return this.dmstQlfctnField;
        }
        set {
            this.dmstQlfctnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class CardProgrammeMode3 {
    
    private string tpField;
    
    private string idField;
    
    private AdditionalData1[] addtlIdField;
    
    /// <remarks/>
    public string Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlId")]
    public AdditionalData1[] AddtlId {
        get {
            return this.addtlIdField;
        }
        set {
            this.addtlIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class TransactionContext10 {
    
    private CardProgrammeMode3 cardPrgrmmApldField;
    
    private Jurisdiction2 jursdctnField;
    
    private SettlementService4 sttlmSvcField;
    
    private Reconciliation3 rcncltnField;
    
    private AdditionalData1[] addtlDataField;
    
    /// <remarks/>
    public CardProgrammeMode3 CardPrgrmmApld {
        get {
            return this.cardPrgrmmApldField;
        }
        set {
            this.cardPrgrmmApldField = value;
        }
    }
    
    /// <remarks/>
    public Jurisdiction2 Jursdctn {
        get {
            return this.jursdctnField;
        }
        set {
            this.jursdctnField = value;
        }
    }
    
    /// <remarks/>
    public SettlementService4 SttlmSvc {
        get {
            return this.sttlmSvcField;
        }
        set {
            this.sttlmSvcField = value;
        }
    }
    
    /// <remarks/>
    public Reconciliation3 Rcncltn {
        get {
            return this.rcncltnField;
        }
        set {
            this.rcncltnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlData")]
    public AdditionalData1[] AddtlData {
        get {
            return this.addtlDataField;
        }
        set {
            this.addtlDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Context17 {
    
    private TransactionContext10 txCntxtField;
    
    /// <remarks/>
    public TransactionContext10 TxCntxt {
        get {
            return this.txCntxtField;
        }
        set {
            this.txCntxtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Address3 {
    
    private string adrLine1Field;
    
    private string adrLine2Field;
    
    private string strtNmField;
    
    private string bldgNbField;
    
    private string pstlCdField;
    
    private string twnNmField;
    
    private string ctrySubDvsnMnrNmField;
    
    private string ctrySubDvsnMjrNmField;
    
    private string ctryField;
    
    /// <remarks/>
    public string AdrLine1 {
        get {
            return this.adrLine1Field;
        }
        set {
            this.adrLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string AdrLine2 {
        get {
            return this.adrLine2Field;
        }
        set {
            this.adrLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string StrtNm {
        get {
            return this.strtNmField;
        }
        set {
            this.strtNmField = value;
        }
    }
    
    /// <remarks/>
    public string BldgNb {
        get {
            return this.bldgNbField;
        }
        set {
            this.bldgNbField = value;
        }
    }
    
    /// <remarks/>
    public string PstlCd {
        get {
            return this.pstlCdField;
        }
        set {
            this.pstlCdField = value;
        }
    }
    
    /// <remarks/>
    public string TwnNm {
        get {
            return this.twnNmField;
        }
        set {
            this.twnNmField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsnMnrNm {
        get {
            return this.ctrySubDvsnMnrNmField;
        }
        set {
            this.ctrySubDvsnMnrNmField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsnMjrNm {
        get {
            return this.ctrySubDvsnMjrNmField;
        }
        set {
            this.ctrySubDvsnMjrNmField = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class CardholderName2 {
    
    private string nmField;
    
    private string gvnNmField;
    
    private string mddlNmField;
    
    private string lastNmField;
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public string GvnNm {
        get {
            return this.gvnNmField;
        }
        set {
            this.gvnNmField = value;
        }
    }
    
    /// <remarks/>
    public string MddlNm {
        get {
            return this.mddlNmField;
        }
        set {
            this.mddlNmField = value;
        }
    }
    
    /// <remarks/>
    public string LastNm {
        get {
            return this.lastNmField;
        }
        set {
            this.lastNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class LocalData7 {
    
    private string langField;
    
    private CardholderName2 crdhldrNmField;
    
    private Address3 adrField;
    
    private AdditionalData1[] addtlDataField;
    
    /// <remarks/>
    public string Lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    public CardholderName2 CrdhldrNm {
        get {
            return this.crdhldrNmField;
        }
        set {
            this.crdhldrNmField = value;
        }
    }
    
    /// <remarks/>
    public Address3 Adr {
        get {
            return this.adrField;
        }
        set {
            this.adrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlData")]
    public AdditionalData1[] AddtlData {
        get {
            return this.addtlDataField;
        }
        set {
            this.addtlDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Contact1 {
    
    private string nmField;
    
    private string homePhneNbField;
    
    private string bizPhneNbField;
    
    private string mobPhneNbField;
    
    private string othrPhneNbField;
    
    private string prsnlEmailAdrField;
    
    private string bizEmailAdrField;
    
    private string othrEmailAdrField;
    
    private string langField;
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public string HomePhneNb {
        get {
            return this.homePhneNbField;
        }
        set {
            this.homePhneNbField = value;
        }
    }
    
    /// <remarks/>
    public string BizPhneNb {
        get {
            return this.bizPhneNbField;
        }
        set {
            this.bizPhneNbField = value;
        }
    }
    
    /// <remarks/>
    public string MobPhneNb {
        get {
            return this.mobPhneNbField;
        }
        set {
            this.mobPhneNbField = value;
        }
    }
    
    /// <remarks/>
    public string OthrPhneNb {
        get {
            return this.othrPhneNbField;
        }
        set {
            this.othrPhneNbField = value;
        }
    }
    
    /// <remarks/>
    public string PrsnlEmailAdr {
        get {
            return this.prsnlEmailAdrField;
        }
        set {
            this.prsnlEmailAdrField = value;
        }
    }
    
    /// <remarks/>
    public string BizEmailAdr {
        get {
            return this.bizEmailAdrField;
        }
        set {
            this.bizEmailAdrField = value;
        }
    }
    
    /// <remarks/>
    public string OthrEmailAdr {
        get {
            return this.othrEmailAdrField;
        }
        set {
            this.othrEmailAdrField = value;
        }
    }
    
    /// <remarks/>
    public string Lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Address2 {
    
    private string adrLine1Field;
    
    private string adrLine2Field;
    
    private string strtNmField;
    
    private string bldgNbField;
    
    private string pstlCdField;
    
    private string twnNmField;
    
    private string ctrySubDvsnMnrField;
    
    private string ctrySubDvsnMjrField;
    
    private string ctrySubDvsnMjrNmField;
    
    private string ctrySubDvsnMnrNmField;
    
    private string ctryField;
    
    /// <remarks/>
    public string AdrLine1 {
        get {
            return this.adrLine1Field;
        }
        set {
            this.adrLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string AdrLine2 {
        get {
            return this.adrLine2Field;
        }
        set {
            this.adrLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string StrtNm {
        get {
            return this.strtNmField;
        }
        set {
            this.strtNmField = value;
        }
    }
    
    /// <remarks/>
    public string BldgNb {
        get {
            return this.bldgNbField;
        }
        set {
            this.bldgNbField = value;
        }
    }
    
    /// <remarks/>
    public string PstlCd {
        get {
            return this.pstlCdField;
        }
        set {
            this.pstlCdField = value;
        }
    }
    
    /// <remarks/>
    public string TwnNm {
        get {
            return this.twnNmField;
        }
        set {
            this.twnNmField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsnMnr {
        get {
            return this.ctrySubDvsnMnrField;
        }
        set {
            this.ctrySubDvsnMnrField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsnMjr {
        get {
            return this.ctrySubDvsnMjrField;
        }
        set {
            this.ctrySubDvsnMjrField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsnMjrNm {
        get {
            return this.ctrySubDvsnMjrNmField;
        }
        set {
            this.ctrySubDvsnMjrNmField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsnMnrNm {
        get {
            return this.ctrySubDvsnMnrNmField;
        }
        set {
            this.ctrySubDvsnMnrNmField = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Authority1 {
    
    private string ctryField;
    
    private string ctrySubDvsnMjrField;
    
    private string ctrySubDvsnMnrField;
    
    private string ctrySubDvsnMjrNmField;
    
    private string ctrySubDvsnMnrNmField;
    
    private string nmField;
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsnMjr {
        get {
            return this.ctrySubDvsnMjrField;
        }
        set {
            this.ctrySubDvsnMjrField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsnMnr {
        get {
            return this.ctrySubDvsnMnrField;
        }
        set {
            this.ctrySubDvsnMnrField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsnMjrNm {
        get {
            return this.ctrySubDvsnMjrNmField;
        }
        set {
            this.ctrySubDvsnMjrNmField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsnMnrNm {
        get {
            return this.ctrySubDvsnMnrNmField;
        }
        set {
            this.ctrySubDvsnMnrNmField = value;
        }
    }
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Credentials2 {
    
    private Identification3Code idCdField;
    
    private string othrIdCdField;
    
    private string idValField;
    
    private string idXpryDtField;
    
    private Authority1 assgnrAuthrtyField;
    
    /// <remarks/>
    public Identification3Code IdCd {
        get {
            return this.idCdField;
        }
        set {
            this.idCdField = value;
        }
    }
    
    /// <remarks/>
    public string OthrIdCd {
        get {
            return this.othrIdCdField;
        }
        set {
            this.othrIdCdField = value;
        }
    }
    
    /// <remarks/>
    public string IdVal {
        get {
            return this.idValField;
        }
        set {
            this.idValField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYearMonth")]
    public string IdXpryDt {
        get {
            return this.idXpryDtField;
        }
        set {
            this.idXpryDtField = value;
        }
    }
    
    /// <remarks/>
    public Authority1 AssgnrAuthrty {
        get {
            return this.assgnrAuthrtyField;
        }
        set {
            this.assgnrAuthrtyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum Identification3Code {
    
    /// <remarks/>
    DRID,
    
    /// <remarks/>
    NTID,
    
    /// <remarks/>
    PASS,
    
    /// <remarks/>
    SSYN,
    
    /// <remarks/>
    ARNB,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    EMAL,
    
    /// <remarks/>
    PHNB,
    
    /// <remarks/>
    CUID,
    
    /// <remarks/>
    TXID,
    
    /// <remarks/>
    PRXY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class CardholderName3 {
    
    private string nmField;
    
    private string gvnNmField;
    
    private string mddlNmField;
    
    private string lastNmField;
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public string GvnNm {
        get {
            return this.gvnNmField;
        }
        set {
            this.gvnNmField = value;
        }
    }
    
    /// <remarks/>
    public string MddlNm {
        get {
            return this.mddlNmField;
        }
        set {
            this.mddlNmField = value;
        }
    }
    
    /// <remarks/>
    public string LastNm {
        get {
            return this.lastNmField;
        }
        set {
            this.lastNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Cardholder19 {
    
    private CardholderName3 crdhldrNmField;
    
    private Credentials2[] idField;
    
    private Address2 adrField;
    
    private Contact1 ctctInfField;
    
    private System.DateTime dtOfBirthField;
    
    private bool dtOfBirthFieldSpecified;
    
    private bool hghValCstmrIndField;
    
    private bool hghValCstmrIndFieldSpecified;
    
    private AdditionalData1[] addtlDataField;
    
    private LocalData7 lclDataField;
    
    /// <remarks/>
    public CardholderName3 CrdhldrNm {
        get {
            return this.crdhldrNmField;
        }
        set {
            this.crdhldrNmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Id")]
    public Credentials2[] Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public Address2 Adr {
        get {
            return this.adrField;
        }
        set {
            this.adrField = value;
        }
    }
    
    /// <remarks/>
    public Contact1 CtctInf {
        get {
            return this.ctctInfField;
        }
        set {
            this.ctctInfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DtOfBirth {
        get {
            return this.dtOfBirthField;
        }
        set {
            this.dtOfBirthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DtOfBirthSpecified {
        get {
            return this.dtOfBirthFieldSpecified;
        }
        set {
            this.dtOfBirthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool HghValCstmrInd {
        get {
            return this.hghValCstmrIndField;
        }
        set {
            this.hghValCstmrIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HghValCstmrIndSpecified {
        get {
            return this.hghValCstmrIndFieldSpecified;
        }
        set {
            this.hghValCstmrIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlData")]
    public AdditionalData1[] AddtlData {
        get {
            return this.addtlDataField;
        }
        set {
            this.addtlDataField = value;
        }
    }
    
    /// <remarks/>
    public LocalData7 LclData {
        get {
            return this.lclDataField;
        }
        set {
            this.lclDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Token2 {
    
    private string pmtTknField;
    
    private string tknXpryDtField;
    
    private string tknRqstrIdField;
    
    private string tknAssrncDataField;
    
    private string tknAssrncMtdField;
    
    private bool tknInittdIndField;
    
    private bool tknInittdIndFieldSpecified;
    
    private StorageLocation1Code storgLctnField;
    
    private bool storgLctnFieldSpecified;
    
    private string othrStorgLctnField;
    
    private ProtectionMethod1Code prtcnMtdField;
    
    private bool prtcnMtdFieldSpecified;
    
    private string othrPrtcnMtdField;
    
    private AdditionalData1[] addtlDataField;
    
    /// <remarks/>
    public string PmtTkn {
        get {
            return this.pmtTknField;
        }
        set {
            this.pmtTknField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYearMonth")]
    public string TknXpryDt {
        get {
            return this.tknXpryDtField;
        }
        set {
            this.tknXpryDtField = value;
        }
    }
    
    /// <remarks/>
    public string TknRqstrId {
        get {
            return this.tknRqstrIdField;
        }
        set {
            this.tknRqstrIdField = value;
        }
    }
    
    /// <remarks/>
    public string TknAssrncData {
        get {
            return this.tknAssrncDataField;
        }
        set {
            this.tknAssrncDataField = value;
        }
    }
    
    /// <remarks/>
    public string TknAssrncMtd {
        get {
            return this.tknAssrncMtdField;
        }
        set {
            this.tknAssrncMtdField = value;
        }
    }
    
    /// <remarks/>
    public bool TknInittdInd {
        get {
            return this.tknInittdIndField;
        }
        set {
            this.tknInittdIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TknInittdIndSpecified {
        get {
            return this.tknInittdIndFieldSpecified;
        }
        set {
            this.tknInittdIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public StorageLocation1Code StorgLctn {
        get {
            return this.storgLctnField;
        }
        set {
            this.storgLctnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StorgLctnSpecified {
        get {
            return this.storgLctnFieldSpecified;
        }
        set {
            this.storgLctnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OthrStorgLctn {
        get {
            return this.othrStorgLctnField;
        }
        set {
            this.othrStorgLctnField = value;
        }
    }
    
    /// <remarks/>
    public ProtectionMethod1Code PrtcnMtd {
        get {
            return this.prtcnMtdField;
        }
        set {
            this.prtcnMtdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrtcnMtdSpecified {
        get {
            return this.prtcnMtdFieldSpecified;
        }
        set {
            this.prtcnMtdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OthrPrtcnMtd {
        get {
            return this.othrPrtcnMtdField;
        }
        set {
            this.othrPrtcnMtdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlData")]
    public AdditionalData1[] AddtlData {
        get {
            return this.addtlDataField;
        }
        set {
            this.addtlDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum StorageLocation1Code {
    
    /// <remarks/>
    CAWL,
    
    /// <remarks/>
    DVCE,
    
    /// <remarks/>
    ISWL,
    
    /// <remarks/>
    ONFL,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    TPWL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum ProtectionMethod1Code {
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    SELM,
    
    /// <remarks/>
    SNCL,
    
    /// <remarks/>
    SOFT,
    
    /// <remarks/>
    TEEN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class CardData8 {
    
    private string pANField;
    
    private bool prtctdPANIndField;
    
    private bool prtctdPANIndFieldSpecified;
    
    private string cardSeqNbField;
    
    private string fctvDtField;
    
    private string xpryDtField;
    
    private string pmtAcctRefField;
    
    private string pANRefIdrField;
    
    private string pANAcctRgField;
    
    private string cardCtryCdField;
    
    private string cardPdctTpField;
    
    private string cardPdctSubTpField;
    
    private string cardPrtflIdrField;
    
    private AdditionalData1[] addtlCardDataField;
    
    /// <remarks/>
    public string PAN {
        get {
            return this.pANField;
        }
        set {
            this.pANField = value;
        }
    }
    
    /// <remarks/>
    public bool PrtctdPANInd {
        get {
            return this.prtctdPANIndField;
        }
        set {
            this.prtctdPANIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrtctdPANIndSpecified {
        get {
            return this.prtctdPANIndFieldSpecified;
        }
        set {
            this.prtctdPANIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string CardSeqNb {
        get {
            return this.cardSeqNbField;
        }
        set {
            this.cardSeqNbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYearMonth")]
    public string FctvDt {
        get {
            return this.fctvDtField;
        }
        set {
            this.fctvDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYearMonth")]
    public string XpryDt {
        get {
            return this.xpryDtField;
        }
        set {
            this.xpryDtField = value;
        }
    }
    
    /// <remarks/>
    public string PmtAcctRef {
        get {
            return this.pmtAcctRefField;
        }
        set {
            this.pmtAcctRefField = value;
        }
    }
    
    /// <remarks/>
    public string PANRefIdr {
        get {
            return this.pANRefIdrField;
        }
        set {
            this.pANRefIdrField = value;
        }
    }
    
    /// <remarks/>
    public string PANAcctRg {
        get {
            return this.pANAcctRgField;
        }
        set {
            this.pANAcctRgField = value;
        }
    }
    
    /// <remarks/>
    public string CardCtryCd {
        get {
            return this.cardCtryCdField;
        }
        set {
            this.cardCtryCdField = value;
        }
    }
    
    /// <remarks/>
    public string CardPdctTp {
        get {
            return this.cardPdctTpField;
        }
        set {
            this.cardPdctTpField = value;
        }
    }
    
    /// <remarks/>
    public string CardPdctSubTp {
        get {
            return this.cardPdctSubTpField;
        }
        set {
            this.cardPdctSubTpField = value;
        }
    }
    
    /// <remarks/>
    public string CardPrtflIdr {
        get {
            return this.cardPrtflIdrField;
        }
        set {
            this.cardPrtflIdrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlCardData")]
    public AdditionalData1[] AddtlCardData {
        get {
            return this.addtlCardDataField;
        }
        set {
            this.addtlCardDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class LocalData1 {
    
    private string langField;
    
    private string shrtNmField;
    
    private string lglCorpNmField;
    
    private AdditionalData1[] addtlDataField;
    
    /// <remarks/>
    public string Lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    public string ShrtNm {
        get {
            return this.shrtNmField;
        }
        set {
            this.shrtNmField = value;
        }
    }
    
    /// <remarks/>
    public string LglCorpNm {
        get {
            return this.lglCorpNmField;
        }
        set {
            this.lglCorpNmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlData")]
    public AdditionalData1[] AddtlData {
        get {
            return this.addtlDataField;
        }
        set {
            this.addtlDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class PartyIdentification263 {
    
    private string idField;
    
    private string assgnrField;
    
    private string ctryField;
    
    private string shrtNmField;
    
    private string lglCorpNmField;
    
    private AdditionalData1 addtlIdField;
    
    private LocalData1 lclDataField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Assgnr {
        get {
            return this.assgnrField;
        }
        set {
            this.assgnrField = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <remarks/>
    public string ShrtNm {
        get {
            return this.shrtNmField;
        }
        set {
            this.shrtNmField = value;
        }
    }
    
    /// <remarks/>
    public string LglCorpNm {
        get {
            return this.lglCorpNmField;
        }
        set {
            this.lglCorpNmField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalData1 AddtlId {
        get {
            return this.addtlIdField;
        }
        set {
            this.addtlIdField = value;
        }
    }
    
    /// <remarks/>
    public LocalData1 LclData {
        get {
            return this.lclDataField;
        }
        set {
            this.lclDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Environment28 {
    
    private PartyIdentification263 acqrrField;
    
    private PartyIdentification263 orgtrField;
    
    private PartyIdentification263 sndrField;
    
    private PartyIdentification263 rcvrField;
    
    private PartyIdentification263 dstnField;
    
    private PartyIdentification263 issrField;
    
    private CardData8 cardField;
    
    private Token2 tknField;
    
    private Cardholder19 crdhldrField;
    
    /// <remarks/>
    public PartyIdentification263 Acqrr {
        get {
            return this.acqrrField;
        }
        set {
            this.acqrrField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification263 Orgtr {
        get {
            return this.orgtrField;
        }
        set {
            this.orgtrField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification263 Sndr {
        get {
            return this.sndrField;
        }
        set {
            this.sndrField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification263 Rcvr {
        get {
            return this.rcvrField;
        }
        set {
            this.rcvrField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification263 Dstn {
        get {
            return this.dstnField;
        }
        set {
            this.dstnField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification263 Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public CardData8 Card {
        get {
            return this.cardField;
        }
        set {
            this.cardField = value;
        }
    }
    
    /// <remarks/>
    public Token2 Tkn {
        get {
            return this.tknField;
        }
        set {
            this.tknField = value;
        }
    }
    
    /// <remarks/>
    public Cardholder19 Crdhldr {
        get {
            return this.crdhldrField;
        }
        set {
            this.crdhldrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class FraudDispositionInitiation2 {
    
    private Environment28 envtField;
    
    private Context17 cntxtField;
    
    private Transaction128 txField;
    
    private FraudDispositionStatus2 frdDspstnStsField;
    
    private SupplementaryData1[] splmtryDataField;
    
    /// <remarks/>
    public Environment28 Envt {
        get {
            return this.envtField;
        }
        set {
            this.envtField = value;
        }
    }
    
    /// <remarks/>
    public Context17 Cntxt {
        get {
            return this.cntxtField;
        }
        set {
            this.cntxtField = value;
        }
    }
    
    /// <remarks/>
    public Transaction128 Tx {
        get {
            return this.txField;
        }
        set {
            this.txField = value;
        }
    }
    
    /// <remarks/>
    public FraudDispositionStatus2 FrdDspstnSts {
        get {
            return this.frdDspstnStsField;
        }
        set {
            this.frdDspstnStsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
    public SupplementaryData1[] SplmtryData {
        get {
            return this.splmtryDataField;
        }
        set {
            this.splmtryDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class Traceability9 {
    
    private GenericIdentification183 rlayIdField;
    
    private System.DateTime tracDtTmInField;
    
    private bool tracDtTmInFieldSpecified;
    
    private System.DateTime tracDtTmOutField;
    
    private bool tracDtTmOutFieldSpecified;
    
    /// <remarks/>
    public GenericIdentification183 RlayId {
        get {
            return this.rlayIdField;
        }
        set {
            this.rlayIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TracDtTmIn {
        get {
            return this.tracDtTmInField;
        }
        set {
            this.tracDtTmInField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TracDtTmInSpecified {
        get {
            return this.tracDtTmInFieldSpecified;
        }
        set {
            this.tracDtTmInFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TracDtTmOut {
        get {
            return this.tracDtTmOutField;
        }
        set {
            this.tracDtTmOutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TracDtTmOutSpecified {
        get {
            return this.tracDtTmOutFieldSpecified;
        }
        set {
            this.tracDtTmOutFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public partial class GenericIdentification183 {
    
    private string idField;
    
    private PartyType17Code tpField;
    
    private bool tpFieldSpecified;
    
    private string othrTpField;
    
    private PartyType18Code assgnrField;
    
    private bool assgnrFieldSpecified;
    
    private string ctryField;
    
    private string shrtNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public PartyType17Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TpSpecified {
        get {
            return this.tpFieldSpecified;
        }
        set {
            this.tpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OthrTp {
        get {
            return this.othrTpField;
        }
        set {
            this.othrTpField = value;
        }
    }
    
    /// <remarks/>
    public PartyType18Code Assgnr {
        get {
            return this.assgnrField;
        }
        set {
            this.assgnrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AssgnrSpecified {
        get {
            return this.assgnrFieldSpecified;
        }
        set {
            this.assgnrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <remarks/>
    public string ShrtNm {
        get {
            return this.shrtNmField;
        }
        set {
            this.shrtNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum PartyType17Code {
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    ACQR,
    
    /// <remarks/>
    ACQP,
    
    /// <remarks/>
    CISS,
    
    /// <remarks/>
    CISP,
    
    /// <remarks/>
    AGNT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:cafr.003.001.02")]
public enum PartyType18Code {
    
    /// <remarks/>
    ACQR,
    
    /// <remarks/>
    CISS,
    
    /// <remarks/>
    CSCH,
    
    /// <remarks/>
    AGNT,
}
