//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03", IsNullable=false)]
public partial class Document {
    
    private NetworkManagementResponseV03 ntwkMgmtRspnField;
    
    /// <remarks/>
    public NetworkManagementResponseV03 NtwkMgmtRspn {
        get {
            return this.ntwkMgmtRspnField;
        }
        set {
            this.ntwkMgmtRspnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class NetworkManagementResponseV03 {
    
    private Header63 hdrField;
    
    private NetworkManagementResponse2 bodyField;
    
    private ContentInformationType20 sctyTrlrField;
    
    /// <remarks/>
    public Header63 Hdr {
        get {
            return this.hdrField;
        }
        set {
            this.hdrField = value;
        }
    }
    
    /// <remarks/>
    public NetworkManagementResponse2 Body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    public ContentInformationType20 SctyTrlr {
        get {
            return this.sctyTrlrField;
        }
        set {
            this.sctyTrlrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class Header63 {
    
    private MessageFunction23Code msgFctnField;
    
    private string prtcolVrsnField;
    
    private string xchgIdField;
    
    private string reTrnsmssnCntrField;
    
    private System.DateTime creDtTmField;
    
    private BatchManagementInformation1 btchMgmtInfField;
    
    private GenericIdentification183 initgPtyField;
    
    private GenericIdentification183 rcptPtyField;
    
    private AdditionalData1[] tracDataField;
    
    private Traceability9[] tracbltField;
    
    /// <remarks/>
    public MessageFunction23Code MsgFctn {
        get {
            return this.msgFctnField;
        }
        set {
            this.msgFctnField = value;
        }
    }
    
    /// <remarks/>
    public string PrtcolVrsn {
        get {
            return this.prtcolVrsnField;
        }
        set {
            this.prtcolVrsnField = value;
        }
    }
    
    /// <remarks/>
    public string XchgId {
        get {
            return this.xchgIdField;
        }
        set {
            this.xchgIdField = value;
        }
    }
    
    /// <remarks/>
    public string ReTrnsmssnCntr {
        get {
            return this.reTrnsmssnCntrField;
        }
        set {
            this.reTrnsmssnCntrField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
    
    /// <remarks/>
    public BatchManagementInformation1 BtchMgmtInf {
        get {
            return this.btchMgmtInfField;
        }
        set {
            this.btchMgmtInfField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification183 InitgPty {
        get {
            return this.initgPtyField;
        }
        set {
            this.initgPtyField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification183 RcptPty {
        get {
            return this.rcptPtyField;
        }
        set {
            this.rcptPtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TracData")]
    public AdditionalData1[] TracData {
        get {
            return this.tracDataField;
        }
        set {
            this.tracDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tracblt")]
    public Traceability9[] Tracblt {
        get {
            return this.tracbltField;
        }
        set {
            this.tracbltField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum MessageFunction23Code {
    
    /// <remarks/>
    ADVC,
    
    /// <remarks/>
    REQU,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class BatchManagementInformation1 {
    
    private string colltnIdField;
    
    private string btchIdField;
    
    private string msgSeqNbField;
    
    private byte[] msgChcksmInptValField;
    
    /// <remarks/>
    public string ColltnId {
        get {
            return this.colltnIdField;
        }
        set {
            this.colltnIdField = value;
        }
    }
    
    /// <remarks/>
    public string BtchId {
        get {
            return this.btchIdField;
        }
        set {
            this.btchIdField = value;
        }
    }
    
    /// <remarks/>
    public string MsgSeqNb {
        get {
            return this.msgSeqNbField;
        }
        set {
            this.msgSeqNbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] MsgChcksmInptVal {
        get {
            return this.msgChcksmInptValField;
        }
        set {
            this.msgChcksmInptValField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class MACData1 {
    
    private string ctrlField;
    
    private string keySetIdrField;
    
    private string drvdInfField;
    
    private string algoField;
    
    private string keyLngthField;
    
    private string keyPrtcnField;
    
    private string keyIndxField;
    
    private string pddgMtdField;
    
    private string initlstnVctrField;
    
    /// <remarks/>
    public string Ctrl {
        get {
            return this.ctrlField;
        }
        set {
            this.ctrlField = value;
        }
    }
    
    /// <remarks/>
    public string KeySetIdr {
        get {
            return this.keySetIdrField;
        }
        set {
            this.keySetIdrField = value;
        }
    }
    
    /// <remarks/>
    public string DrvdInf {
        get {
            return this.drvdInfField;
        }
        set {
            this.drvdInfField = value;
        }
    }
    
    /// <remarks/>
    public string Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public string KeyLngth {
        get {
            return this.keyLngthField;
        }
        set {
            this.keyLngthField = value;
        }
    }
    
    /// <remarks/>
    public string KeyPrtcn {
        get {
            return this.keyPrtcnField;
        }
        set {
            this.keyPrtcnField = value;
        }
    }
    
    /// <remarks/>
    public string KeyIndx {
        get {
            return this.keyIndxField;
        }
        set {
            this.keyIndxField = value;
        }
    }
    
    /// <remarks/>
    public string PddgMtd {
        get {
            return this.pddgMtdField;
        }
        set {
            this.pddgMtdField = value;
        }
    }
    
    /// <remarks/>
    public string InitlstnVctr {
        get {
            return this.initlstnVctrField;
        }
        set {
            this.initlstnVctrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class ContentInformationType20 {
    
    private MACData1 mACDataField;
    
    private string mACField;
    
    /// <remarks/>
    public MACData1 MACData {
        get {
            return this.mACDataField;
        }
        set {
            this.mACDataField = value;
        }
    }
    
    /// <remarks/>
    public string MAC {
        get {
            return this.mACField;
        }
        set {
            this.mACField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class SupplementaryData1 {
    
    private string plcAndNmField;
    
    private System.Xml.XmlElement envlpField;
    
    /// <remarks/>
    public string PlcAndNm {
        get {
            return this.plcAndNmField;
        }
        set {
            this.plcAndNmField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Envlp {
        get {
            return this.envlpField;
        }
        set {
            this.envlpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class AdditionalInformation29 {
    
    private PartyType22Code rcptField;
    
    private bool rcptFieldSpecified;
    
    private string othrRcptField;
    
    private UserInterface6Code[] trgtField;
    
    private string othrTrgtField;
    
    private OutputFormat4Code frmtField;
    
    private bool frmtFieldSpecified;
    
    private string othrFrmtField;
    
    private string tpField;
    
    private string langField;
    
    private string valField;
    
    /// <remarks/>
    public PartyType22Code Rcpt {
        get {
            return this.rcptField;
        }
        set {
            this.rcptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RcptSpecified {
        get {
            return this.rcptFieldSpecified;
        }
        set {
            this.rcptFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OthrRcpt {
        get {
            return this.othrRcptField;
        }
        set {
            this.othrRcptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Trgt")]
    public UserInterface6Code[] Trgt {
        get {
            return this.trgtField;
        }
        set {
            this.trgtField = value;
        }
    }
    
    /// <remarks/>
    public string OthrTrgt {
        get {
            return this.othrTrgtField;
        }
        set {
            this.othrTrgtField = value;
        }
    }
    
    /// <remarks/>
    public OutputFormat4Code Frmt {
        get {
            return this.frmtField;
        }
        set {
            this.frmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FrmtSpecified {
        get {
            return this.frmtFieldSpecified;
        }
        set {
            this.frmtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OthrFrmt {
        get {
            return this.othrFrmtField;
        }
        set {
            this.othrFrmtField = value;
        }
    }
    
    /// <remarks/>
    public string Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    public string Val {
        get {
            return this.valField;
        }
        set {
            this.valField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum PartyType22Code {
    
    /// <remarks/>
    CRDH,
    
    /// <remarks/>
    MERC,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    AGNT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum UserInterface6Code {
    
    /// <remarks/>
    CDSP,
    
    /// <remarks/>
    CRCP,
    
    /// <remarks/>
    MDSP,
    
    /// <remarks/>
    MRCP,
    
    /// <remarks/>
    CRDO,
    
    /// <remarks/>
    FILE,
    
    /// <remarks/>
    CHAP,
    
    /// <remarks/>
    MRAP,
    
    /// <remarks/>
    MRIN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum OutputFormat4Code {
    
    /// <remarks/>
    FLNM,
    
    /// <remarks/>
    MREF,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    SMSI,
    
    /// <remarks/>
    TEXT,
    
    /// <remarks/>
    URLI,
    
    /// <remarks/>
    HTML,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class Content1 {
    
    private string valField;
    
    private byte[] sgntrField;
    
    private string certIdField;
    
    /// <remarks/>
    public string Val {
        get {
            return this.valField;
        }
        set {
            this.valField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Sgntr {
        get {
            return this.sgntrField;
        }
        set {
            this.sgntrField = value;
        }
    }
    
    /// <remarks/>
    public string CertId {
        get {
            return this.certIdField;
        }
        set {
            this.certIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class AdditionalAction1 {
    
    private ActionType10Code tpField;
    
    private bool tpFieldSpecified;
    
    private PartyType21Code dstnField;
    
    private bool dstnFieldSpecified;
    
    private string othrDstnField;
    
    private ActionDestination1Code dstnTpField;
    
    private bool dstnTpFieldSpecified;
    
    private string othrDstnTpField;
    
    private string dstnAdrField;
    
    private OutputFormat4Code frmtField;
    
    private bool frmtFieldSpecified;
    
    private string othrFrmtField;
    
    private Content1 cnttField;
    
    /// <remarks/>
    public ActionType10Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TpSpecified {
        get {
            return this.tpFieldSpecified;
        }
        set {
            this.tpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PartyType21Code Dstn {
        get {
            return this.dstnField;
        }
        set {
            this.dstnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DstnSpecified {
        get {
            return this.dstnFieldSpecified;
        }
        set {
            this.dstnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OthrDstn {
        get {
            return this.othrDstnField;
        }
        set {
            this.othrDstnField = value;
        }
    }
    
    /// <remarks/>
    public ActionDestination1Code DstnTp {
        get {
            return this.dstnTpField;
        }
        set {
            this.dstnTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DstnTpSpecified {
        get {
            return this.dstnTpFieldSpecified;
        }
        set {
            this.dstnTpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OthrDstnTp {
        get {
            return this.othrDstnTpField;
        }
        set {
            this.othrDstnTpField = value;
        }
    }
    
    /// <remarks/>
    public string DstnAdr {
        get {
            return this.dstnAdrField;
        }
        set {
            this.dstnAdrField = value;
        }
    }
    
    /// <remarks/>
    public OutputFormat4Code Frmt {
        get {
            return this.frmtField;
        }
        set {
            this.frmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FrmtSpecified {
        get {
            return this.frmtFieldSpecified;
        }
        set {
            this.frmtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OthrFrmt {
        get {
            return this.othrFrmtField;
        }
        set {
            this.othrFrmtField = value;
        }
    }
    
    /// <remarks/>
    public Content1 Cntt {
        get {
            return this.cnttField;
        }
        set {
            this.cnttField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum ActionType10Code {
    
    /// <remarks/>
    ACTV,
    
    /// <remarks/>
    DEAC,
    
    /// <remarks/>
    DISP,
    
    /// <remarks/>
    FUPD,
    
    /// <remarks/>
    PRNT,
    
    /// <remarks/>
    SNDM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum PartyType21Code {
    
    /// <remarks/>
    ACCP,
    
    /// <remarks/>
    CRDH,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum ActionDestination1Code {
    
    /// <remarks/>
    FILE,
    
    /// <remarks/>
    MOBL,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    PECR,
    
    /// <remarks/>
    POFS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class Contact6 {
    
    private string homePhneNbField;
    
    private string bizPhneNbField;
    
    private string mobPhneNbField;
    
    private string othrPhneNbField;
    
    private string prsnlEmailAdrField;
    
    private string bizEmailAdrField;
    
    private string othrEmailAdrField;
    
    private string homeFaxNbField;
    
    private string bizFaxNbField;
    
    private string uRLAdrField;
    
    private string langField;
    
    /// <remarks/>
    public string HomePhneNb {
        get {
            return this.homePhneNbField;
        }
        set {
            this.homePhneNbField = value;
        }
    }
    
    /// <remarks/>
    public string BizPhneNb {
        get {
            return this.bizPhneNbField;
        }
        set {
            this.bizPhneNbField = value;
        }
    }
    
    /// <remarks/>
    public string MobPhneNb {
        get {
            return this.mobPhneNbField;
        }
        set {
            this.mobPhneNbField = value;
        }
    }
    
    /// <remarks/>
    public string OthrPhneNb {
        get {
            return this.othrPhneNbField;
        }
        set {
            this.othrPhneNbField = value;
        }
    }
    
    /// <remarks/>
    public string PrsnlEmailAdr {
        get {
            return this.prsnlEmailAdrField;
        }
        set {
            this.prsnlEmailAdrField = value;
        }
    }
    
    /// <remarks/>
    public string BizEmailAdr {
        get {
            return this.bizEmailAdrField;
        }
        set {
            this.bizEmailAdrField = value;
        }
    }
    
    /// <remarks/>
    public string OthrEmailAdr {
        get {
            return this.othrEmailAdrField;
        }
        set {
            this.othrEmailAdrField = value;
        }
    }
    
    /// <remarks/>
    public string HomeFaxNb {
        get {
            return this.homeFaxNbField;
        }
        set {
            this.homeFaxNbField = value;
        }
    }
    
    /// <remarks/>
    public string BizFaxNb {
        get {
            return this.bizFaxNbField;
        }
        set {
            this.bizFaxNbField = value;
        }
    }
    
    /// <remarks/>
    public string URLAdr {
        get {
            return this.uRLAdrField;
        }
        set {
            this.uRLAdrField = value;
        }
    }
    
    /// <remarks/>
    public string Lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class Action13 {
    
    private PartyType20Code dstnField;
    
    private bool dstnFieldSpecified;
    
    private ActionType11Code actnTpField;
    
    private bool actnTpFieldSpecified;
    
    private string othrActnTpField;
    
    private Contact6 ctctField;
    
    private AdditionalData1[] addtlDataField;
    
    /// <remarks/>
    public PartyType20Code Dstn {
        get {
            return this.dstnField;
        }
        set {
            this.dstnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DstnSpecified {
        get {
            return this.dstnFieldSpecified;
        }
        set {
            this.dstnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ActionType11Code ActnTp {
        get {
            return this.actnTpField;
        }
        set {
            this.actnTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActnTpSpecified {
        get {
            return this.actnTpFieldSpecified;
        }
        set {
            this.actnTpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OthrActnTp {
        get {
            return this.othrActnTpField;
        }
        set {
            this.othrActnTpField = value;
        }
    }
    
    /// <remarks/>
    public Contact6 Ctct {
        get {
            return this.ctctField;
        }
        set {
            this.ctctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlData")]
    public AdditionalData1[] AddtlData {
        get {
            return this.addtlDataField;
        }
        set {
            this.addtlDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum PartyType20Code {
    
    /// <remarks/>
    ACCP,
    
    /// <remarks/>
    ACQR,
    
    /// <remarks/>
    CRDH,
    
    /// <remarks/>
    CISS,
    
    /// <remarks/>
    AGNT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum ActionType11Code {
    
    /// <remarks/>
    CNTI,
    
    /// <remarks/>
    CNIS,
    
    /// <remarks/>
    CNTA,
    
    /// <remarks/>
    CNAS,
    
    /// <remarks/>
    CPTR,
    
    /// <remarks/>
    CHDV,
    
    /// <remarks/>
    VIPM,
    
    /// <remarks/>
    TRCK,
    
    /// <remarks/>
    TRXR,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    SIGN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class AdditionalData1 {
    
    private string tpField;
    
    private string valField;
    
    /// <remarks/>
    public string Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Val {
        get {
            return this.valField;
        }
        set {
            this.valField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class ErrorDetails2 {
    
    private MessageError1Code msgErrTpField;
    
    private string othrMsgErrTpField;
    
    private string errCdField;
    
    private string errDescField;
    
    private string[] dataElmtInErrField;
    
    /// <remarks/>
    public MessageError1Code MsgErrTp {
        get {
            return this.msgErrTpField;
        }
        set {
            this.msgErrTpField = value;
        }
    }
    
    /// <remarks/>
    public string OthrMsgErrTp {
        get {
            return this.othrMsgErrTpField;
        }
        set {
            this.othrMsgErrTpField = value;
        }
    }
    
    /// <remarks/>
    public string ErrCd {
        get {
            return this.errCdField;
        }
        set {
            this.errCdField = value;
        }
    }
    
    /// <remarks/>
    public string ErrDesc {
        get {
            return this.errDescField;
        }
        set {
            this.errDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataElmtInErr")]
    public string[] DataElmtInErr {
        get {
            return this.dataElmtInErrField;
        }
        set {
            this.dataElmtInErrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum MessageError1Code {
    
    /// <remarks/>
    IDEF,
    
    /// <remarks/>
    IDEL,
    
    /// <remarks/>
    IDEV,
    
    /// <remarks/>
    INME,
    
    /// <remarks/>
    INMF,
    
    /// <remarks/>
    MEPE,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    PRVE,
    
    /// <remarks/>
    RDEM,
    
    /// <remarks/>
    SECU,
    
    /// <remarks/>
    UDFD,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    ITDE,
    
    /// <remarks/>
    DUME,
    
    /// <remarks/>
    IDWM,
    
    /// <remarks/>
    IDRM,
    
    /// <remarks/>
    IBAT,
    
    /// <remarks/>
    ICOL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class ResultData7 {
    
    private Response8Code rsltField;
    
    private bool rsltFieldSpecified;
    
    private string othrRsltField;
    
    private string rsltDtlsField;
    
    private string othrRsltDtlsField;
    
    private bool tempScrCardDataReusePrtdField;
    
    private bool tempScrCardDataReusePrtdFieldSpecified;
    
    private AdditionalData1[] addtlRsltInfField;
    
    /// <remarks/>
    public Response8Code Rslt {
        get {
            return this.rsltField;
        }
        set {
            this.rsltField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RsltSpecified {
        get {
            return this.rsltFieldSpecified;
        }
        set {
            this.rsltFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OthrRslt {
        get {
            return this.othrRsltField;
        }
        set {
            this.othrRsltField = value;
        }
    }
    
    /// <remarks/>
    public string RsltDtls {
        get {
            return this.rsltDtlsField;
        }
        set {
            this.rsltDtlsField = value;
        }
    }
    
    /// <remarks/>
    public string OthrRsltDtls {
        get {
            return this.othrRsltDtlsField;
        }
        set {
            this.othrRsltDtlsField = value;
        }
    }
    
    /// <remarks/>
    public bool TempScrCardDataReusePrtd {
        get {
            return this.tempScrCardDataReusePrtdField;
        }
        set {
            this.tempScrCardDataReusePrtdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TempScrCardDataReusePrtdSpecified {
        get {
            return this.tempScrCardDataReusePrtdFieldSpecified;
        }
        set {
            this.tempScrCardDataReusePrtdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlRsltInf")]
    public AdditionalData1[] AddtlRsltInf {
        get {
            return this.addtlRsltInfField;
        }
        set {
            this.addtlRsltInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum Response8Code {
    
    /// <remarks/>
    PRCS,
    
    /// <remarks/>
    UNPR,
    
    /// <remarks/>
    UNRV,
    
    /// <remarks/>
    REJT,
    
    /// <remarks/>
    TECH,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class ApprovalEntity2 {
    
    private string idField;
    
    private PartyType26Code tpField;
    
    private string othrTpField;
    
    private PartyType9Code assgnrField;
    
    private bool assgnrFieldSpecified;
    
    private string ctryField;
    
    private string shrtNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public PartyType26Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string OthrTp {
        get {
            return this.othrTpField;
        }
        set {
            this.othrTpField = value;
        }
    }
    
    /// <remarks/>
    public PartyType9Code Assgnr {
        get {
            return this.assgnrField;
        }
        set {
            this.assgnrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AssgnrSpecified {
        get {
            return this.assgnrFieldSpecified;
        }
        set {
            this.assgnrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <remarks/>
    public string ShrtNm {
        get {
            return this.shrtNmField;
        }
        set {
            this.shrtNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum PartyType26Code {
    
    /// <remarks/>
    ACCP,
    
    /// <remarks/>
    ACQR,
    
    /// <remarks/>
    ICCA,
    
    /// <remarks/>
    CISS,
    
    /// <remarks/>
    DLIS,
    
    /// <remarks/>
    AGNT,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum PartyType9Code {
    
    /// <remarks/>
    ACQR,
    
    /// <remarks/>
    ACQP,
    
    /// <remarks/>
    CISS,
    
    /// <remarks/>
    CISP,
    
    /// <remarks/>
    CSCH,
    
    /// <remarks/>
    SCHP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class ProcessingResult9 {
    
    private ApprovalEntity2 rspnSrcField;
    
    private ResultData7 rsltDataField;
    
    private string apprvlCdField;
    
    private ErrorDetails2[] errDtlField;
    
    private ResultData7 orgnlRsltDataField;
    
    private bool actnReqrdField;
    
    private bool actnReqrdFieldSpecified;
    
    private Action13[] actnField;
    
    private AdditionalAction1[] addtlActnField;
    
    private AdditionalInformation29[] addtlInfField;
    
    /// <remarks/>
    public ApprovalEntity2 RspnSrc {
        get {
            return this.rspnSrcField;
        }
        set {
            this.rspnSrcField = value;
        }
    }
    
    /// <remarks/>
    public ResultData7 RsltData {
        get {
            return this.rsltDataField;
        }
        set {
            this.rsltDataField = value;
        }
    }
    
    /// <remarks/>
    public string ApprvlCd {
        get {
            return this.apprvlCdField;
        }
        set {
            this.apprvlCdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ErrDtl")]
    public ErrorDetails2[] ErrDtl {
        get {
            return this.errDtlField;
        }
        set {
            this.errDtlField = value;
        }
    }
    
    /// <remarks/>
    public ResultData7 OrgnlRsltData {
        get {
            return this.orgnlRsltDataField;
        }
        set {
            this.orgnlRsltDataField = value;
        }
    }
    
    /// <remarks/>
    public bool ActnReqrd {
        get {
            return this.actnReqrdField;
        }
        set {
            this.actnReqrdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActnReqrdSpecified {
        get {
            return this.actnReqrdFieldSpecified;
        }
        set {
            this.actnReqrdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Actn")]
    public Action13[] Actn {
        get {
            return this.actnField;
        }
        set {
            this.actnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlActn")]
    public AdditionalAction1[] AddtlActn {
        get {
            return this.addtlActnField;
        }
        set {
            this.addtlActnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlInf")]
    public AdditionalInformation29[] AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class FeeAmount3 {
    
    private decimal amtField;
    
    private CreditDebit3Code cdtDbtField;
    
    private bool cdtDbtFieldSpecified;
    
    private string ccyField;
    
    private decimal fctvXchgRateField;
    
    private bool fctvXchgRateFieldSpecified;
    
    private System.DateTime convsDtField;
    
    private bool convsDtFieldSpecified;
    
    private System.DateTime convsTmField;
    
    private bool convsTmFieldSpecified;
    
    /// <remarks/>
    public decimal Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <remarks/>
    public CreditDebit3Code CdtDbt {
        get {
            return this.cdtDbtField;
        }
        set {
            this.cdtDbtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CdtDbtSpecified {
        get {
            return this.cdtDbtFieldSpecified;
        }
        set {
            this.cdtDbtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    public decimal FctvXchgRate {
        get {
            return this.fctvXchgRateField;
        }
        set {
            this.fctvXchgRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FctvXchgRateSpecified {
        get {
            return this.fctvXchgRateFieldSpecified;
        }
        set {
            this.fctvXchgRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ConvsDt {
        get {
            return this.convsDtField;
        }
        set {
            this.convsDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConvsDtSpecified {
        get {
            return this.convsDtFieldSpecified;
        }
        set {
            this.convsDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime ConvsTm {
        get {
            return this.convsTmField;
        }
        set {
            this.convsTmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConvsTmSpecified {
        get {
            return this.convsTmFieldSpecified;
        }
        set {
            this.convsTmFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum CreditDebit3Code {
    
    /// <remarks/>
    CRDT,
    
    /// <remarks/>
    DBIT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class AdditionalFee2 {
    
    private TypeOfAmount21Code tpField;
    
    private string othrTpField;
    
    private string feePrgmField;
    
    private string feeDscrptrField;
    
    private FeeAmount3 feeAmtField;
    
    private FeeAmount3 feeRcncltnAmtField;
    
    private string descField;
    
    private AdditionalData1[] addtlDataField;
    
    /// <remarks/>
    public TypeOfAmount21Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string OthrTp {
        get {
            return this.othrTpField;
        }
        set {
            this.othrTpField = value;
        }
    }
    
    /// <remarks/>
    public string FeePrgm {
        get {
            return this.feePrgmField;
        }
        set {
            this.feePrgmField = value;
        }
    }
    
    /// <remarks/>
    public string FeeDscrptr {
        get {
            return this.feeDscrptrField;
        }
        set {
            this.feeDscrptrField = value;
        }
    }
    
    /// <remarks/>
    public FeeAmount3 FeeAmt {
        get {
            return this.feeAmtField;
        }
        set {
            this.feeAmtField = value;
        }
    }
    
    /// <remarks/>
    public FeeAmount3 FeeRcncltnAmt {
        get {
            return this.feeRcncltnAmtField;
        }
        set {
            this.feeRcncltnAmtField = value;
        }
    }
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlData")]
    public AdditionalData1[] AddtlData {
        get {
            return this.addtlDataField;
        }
        set {
            this.addtlDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum TypeOfAmount21Code {
    
    /// <remarks/>
    INTC,
    
    /// <remarks/>
    FEEP,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    FEEA,
    
    /// <remarks/>
    CSIF,
    
    /// <remarks/>
    MXIF,
    
    /// <remarks/>
    MNIF,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class TransactionLifeCycleIdentification2 {
    
    private string idField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class TransactionIdentification12 {
    
    private string sysTracAudtNbField;
    
    private System.DateTime trnsmssnDtTmField;
    
    private string rtrvlRefNbField;
    
    private TransactionLifeCycleIdentification2 lifeCyclTracIdDataField;
    
    /// <remarks/>
    public string SysTracAudtNb {
        get {
            return this.sysTracAudtNbField;
        }
        set {
            this.sysTracAudtNbField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TrnsmssnDtTm {
        get {
            return this.trnsmssnDtTmField;
        }
        set {
            this.trnsmssnDtTmField = value;
        }
    }
    
    /// <remarks/>
    public string RtrvlRefNb {
        get {
            return this.rtrvlRefNbField;
        }
        set {
            this.rtrvlRefNbField = value;
        }
    }
    
    /// <remarks/>
    public TransactionLifeCycleIdentification2 LifeCyclTracIdData {
        get {
            return this.lifeCyclTracIdDataField;
        }
        set {
            this.lifeCyclTracIdDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class Transaction134 {
    
    private NetworkManagementType1Code ntwkMgmtTpField;
    
    private bool ntwkMgmtTpFieldSpecified;
    
    private string othrNtwkMgmtTpField;
    
    private string[] msgRsnField;
    
    private string[] altrnMsgRsnField;
    
    private TransactionIdentification12 txIdField;
    
    private decimal nbOfMsgsField;
    
    private bool nbOfMsgsFieldSpecified;
    
    private decimal maxNbOfMsgsField;
    
    private bool maxNbOfMsgsFieldSpecified;
    
    private AdditionalFee2[] addtlFeeField;
    
    private string txDescField;
    
    private AdditionalData1[] addtlDataField;
    
    /// <remarks/>
    public NetworkManagementType1Code NtwkMgmtTp {
        get {
            return this.ntwkMgmtTpField;
        }
        set {
            this.ntwkMgmtTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NtwkMgmtTpSpecified {
        get {
            return this.ntwkMgmtTpFieldSpecified;
        }
        set {
            this.ntwkMgmtTpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OthrNtwkMgmtTp {
        get {
            return this.othrNtwkMgmtTpField;
        }
        set {
            this.othrNtwkMgmtTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MsgRsn")]
    public string[] MsgRsn {
        get {
            return this.msgRsnField;
        }
        set {
            this.msgRsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AltrnMsgRsn")]
    public string[] AltrnMsgRsn {
        get {
            return this.altrnMsgRsnField;
        }
        set {
            this.altrnMsgRsnField = value;
        }
    }
    
    /// <remarks/>
    public TransactionIdentification12 TxId {
        get {
            return this.txIdField;
        }
        set {
            this.txIdField = value;
        }
    }
    
    /// <remarks/>
    public decimal NbOfMsgs {
        get {
            return this.nbOfMsgsField;
        }
        set {
            this.nbOfMsgsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NbOfMsgsSpecified {
        get {
            return this.nbOfMsgsFieldSpecified;
        }
        set {
            this.nbOfMsgsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal MaxNbOfMsgs {
        get {
            return this.maxNbOfMsgsField;
        }
        set {
            this.maxNbOfMsgsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxNbOfMsgsSpecified {
        get {
            return this.maxNbOfMsgsFieldSpecified;
        }
        set {
            this.maxNbOfMsgsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlFee")]
    public AdditionalFee2[] AddtlFee {
        get {
            return this.addtlFeeField;
        }
        set {
            this.addtlFeeField = value;
        }
    }
    
    /// <remarks/>
    public string TxDesc {
        get {
            return this.txDescField;
        }
        set {
            this.txDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlData")]
    public AdditionalData1[] AddtlData {
        get {
            return this.addtlDataField;
        }
        set {
            this.addtlDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum NetworkManagementType1Code {
    
    /// <remarks/>
    ECTS,
    
    /// <remarks/>
    ESFW,
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    SGNF,
    
    /// <remarks/>
    SGNN,
    
    /// <remarks/>
    DSFW,
    
    /// <remarks/>
    TSUN,
    
    /// <remarks/>
    MOSB,
    
    /// <remarks/>
    SPIN,
    
    /// <remarks/>
    IART,
    
    /// <remarks/>
    SYCL,
    
    /// <remarks/>
    DRBI,
    
    /// <remarks/>
    ERBI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class Reconciliation3 {
    
    private string idField;
    
    private System.DateTime dtField;
    
    private bool dtFieldSpecified;
    
    private string chckptRefField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Dt {
        get {
            return this.dtField;
        }
        set {
            this.dtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DtSpecified {
        get {
            return this.dtFieldSpecified;
        }
        set {
            this.dtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ChckptRef {
        get {
            return this.chckptRefField;
        }
        set {
            this.chckptRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class SettlementReportingEntity1 {
    
    private string tpField;
    
    private string idField;
    
    /// <remarks/>
    public string Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class SettlementServiceDate2 {
    
    private System.DateTime reqdSttlmDtField;
    
    private bool reqdSttlmDtFieldSpecified;
    
    private bool dfrrdSttlmIndField;
    
    private bool dfrrdSttlmIndFieldSpecified;
    
    private System.DateTime sttlmDtField;
    
    private bool sttlmDtFieldSpecified;
    
    private System.DateTime sttlmTmField;
    
    private bool sttlmTmFieldSpecified;
    
    private string sttlmPrdField;
    
    private System.DateTime sttlmCutOffTmField;
    
    private bool sttlmCutOffTmFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ReqdSttlmDt {
        get {
            return this.reqdSttlmDtField;
        }
        set {
            this.reqdSttlmDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReqdSttlmDtSpecified {
        get {
            return this.reqdSttlmDtFieldSpecified;
        }
        set {
            this.reqdSttlmDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool DfrrdSttlmInd {
        get {
            return this.dfrrdSttlmIndField;
        }
        set {
            this.dfrrdSttlmIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DfrrdSttlmIndSpecified {
        get {
            return this.dfrrdSttlmIndFieldSpecified;
        }
        set {
            this.dfrrdSttlmIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime SttlmDt {
        get {
            return this.sttlmDtField;
        }
        set {
            this.sttlmDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SttlmDtSpecified {
        get {
            return this.sttlmDtFieldSpecified;
        }
        set {
            this.sttlmDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime SttlmTm {
        get {
            return this.sttlmTmField;
        }
        set {
            this.sttlmTmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SttlmTmSpecified {
        get {
            return this.sttlmTmFieldSpecified;
        }
        set {
            this.sttlmTmFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string SttlmPrd {
        get {
            return this.sttlmPrdField;
        }
        set {
            this.sttlmPrdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime SttlmCutOffTm {
        get {
            return this.sttlmCutOffTmField;
        }
        set {
            this.sttlmCutOffTmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SttlmCutOffTmSpecified {
        get {
            return this.sttlmCutOffTmFieldSpecified;
        }
        set {
            this.sttlmCutOffTmFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class SettlementServiceMode1 {
    
    private string tpField;
    
    private string idField;
    
    private string shrtNmField;
    
    private Priority3Code sttlmPrtyField;
    
    private bool sttlmPrtyFieldSpecified;
    
    /// <remarks/>
    public string Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string ShrtNm {
        get {
            return this.shrtNmField;
        }
        set {
            this.shrtNmField = value;
        }
    }
    
    /// <remarks/>
    public Priority3Code SttlmPrty {
        get {
            return this.sttlmPrtyField;
        }
        set {
            this.sttlmPrtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SttlmPrtySpecified {
        get {
            return this.sttlmPrtyFieldSpecified;
        }
        set {
            this.sttlmPrtyFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum Priority3Code {
    
    /// <remarks/>
    URGT,
    
    /// <remarks/>
    HIGH,
    
    /// <remarks/>
    NORM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class SettlementService4 {
    
    private SettlementServiceMode1 sttlmSvcApldField;
    
    private SettlementServiceDate2 sttlmSvcDtsField;
    
    private SettlementReportingEntity1 sttlmRptgNttyField;
    
    private AdditionalData1[] addtlSttlmInfField;
    
    /// <remarks/>
    public SettlementServiceMode1 SttlmSvcApld {
        get {
            return this.sttlmSvcApldField;
        }
        set {
            this.sttlmSvcApldField = value;
        }
    }
    
    /// <remarks/>
    public SettlementServiceDate2 SttlmSvcDts {
        get {
            return this.sttlmSvcDtsField;
        }
        set {
            this.sttlmSvcDtsField = value;
        }
    }
    
    /// <remarks/>
    public SettlementReportingEntity1 SttlmRptgNtty {
        get {
            return this.sttlmRptgNttyField;
        }
        set {
            this.sttlmRptgNttyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlSttlmInf")]
    public AdditionalData1[] AddtlSttlmInf {
        get {
            return this.addtlSttlmInfField;
        }
        set {
            this.addtlSttlmInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class Jurisdiction2 {
    
    private bool dmstIndField;
    
    private bool dmstIndFieldSpecified;
    
    private string dmstQlfctnField;
    
    /// <remarks/>
    public bool DmstInd {
        get {
            return this.dmstIndField;
        }
        set {
            this.dmstIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DmstIndSpecified {
        get {
            return this.dmstIndFieldSpecified;
        }
        set {
            this.dmstIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string DmstQlfctn {
        get {
            return this.dmstQlfctnField;
        }
        set {
            this.dmstQlfctnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class CardProgrammeMode3 {
    
    private string tpField;
    
    private string idField;
    
    private AdditionalData1[] addtlIdField;
    
    /// <remarks/>
    public string Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlId")]
    public AdditionalData1[] AddtlId {
        get {
            return this.addtlIdField;
        }
        set {
            this.addtlIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class TransactionContext10 {
    
    private CardProgrammeMode3 cardPrgrmmApldField;
    
    private Jurisdiction2 jursdctnField;
    
    private SettlementService4 sttlmSvcField;
    
    private Reconciliation3 rcncltnField;
    
    private AdditionalData1[] addtlDataField;
    
    /// <remarks/>
    public CardProgrammeMode3 CardPrgrmmApld {
        get {
            return this.cardPrgrmmApldField;
        }
        set {
            this.cardPrgrmmApldField = value;
        }
    }
    
    /// <remarks/>
    public Jurisdiction2 Jursdctn {
        get {
            return this.jursdctnField;
        }
        set {
            this.jursdctnField = value;
        }
    }
    
    /// <remarks/>
    public SettlementService4 SttlmSvc {
        get {
            return this.sttlmSvcField;
        }
        set {
            this.sttlmSvcField = value;
        }
    }
    
    /// <remarks/>
    public Reconciliation3 Rcncltn {
        get {
            return this.rcncltnField;
        }
        set {
            this.rcncltnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlData")]
    public AdditionalData1[] AddtlData {
        get {
            return this.addtlDataField;
        }
        set {
            this.addtlDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class Context17 {
    
    private TransactionContext10 txCntxtField;
    
    /// <remarks/>
    public TransactionContext10 TxCntxt {
        get {
            return this.txCntxtField;
        }
        set {
            this.txCntxtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class NetworkManagementResponse2 {
    
    private Context17 cntxtField;
    
    private Transaction134 txField;
    
    private ProcessingResult9 prcgRsltField;
    
    private SupplementaryData1[] splmtryDataField;
    
    /// <remarks/>
    public Context17 Cntxt {
        get {
            return this.cntxtField;
        }
        set {
            this.cntxtField = value;
        }
    }
    
    /// <remarks/>
    public Transaction134 Tx {
        get {
            return this.txField;
        }
        set {
            this.txField = value;
        }
    }
    
    /// <remarks/>
    public ProcessingResult9 PrcgRslt {
        get {
            return this.prcgRsltField;
        }
        set {
            this.prcgRsltField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
    public SupplementaryData1[] SplmtryData {
        get {
            return this.splmtryDataField;
        }
        set {
            this.splmtryDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class Traceability9 {
    
    private GenericIdentification183 rlayIdField;
    
    private System.DateTime tracDtTmInField;
    
    private bool tracDtTmInFieldSpecified;
    
    private System.DateTime tracDtTmOutField;
    
    private bool tracDtTmOutFieldSpecified;
    
    /// <remarks/>
    public GenericIdentification183 RlayId {
        get {
            return this.rlayIdField;
        }
        set {
            this.rlayIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TracDtTmIn {
        get {
            return this.tracDtTmInField;
        }
        set {
            this.tracDtTmInField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TracDtTmInSpecified {
        get {
            return this.tracDtTmInFieldSpecified;
        }
        set {
            this.tracDtTmInFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TracDtTmOut {
        get {
            return this.tracDtTmOutField;
        }
        set {
            this.tracDtTmOutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TracDtTmOutSpecified {
        get {
            return this.tracDtTmOutFieldSpecified;
        }
        set {
            this.tracDtTmOutFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public partial class GenericIdentification183 {
    
    private string idField;
    
    private PartyType17Code tpField;
    
    private bool tpFieldSpecified;
    
    private string othrTpField;
    
    private PartyType18Code assgnrField;
    
    private bool assgnrFieldSpecified;
    
    private string ctryField;
    
    private string shrtNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public PartyType17Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TpSpecified {
        get {
            return this.tpFieldSpecified;
        }
        set {
            this.tpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OthrTp {
        get {
            return this.othrTpField;
        }
        set {
            this.othrTpField = value;
        }
    }
    
    /// <remarks/>
    public PartyType18Code Assgnr {
        get {
            return this.assgnrField;
        }
        set {
            this.assgnrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AssgnrSpecified {
        get {
            return this.assgnrFieldSpecified;
        }
        set {
            this.assgnrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <remarks/>
    public string ShrtNm {
        get {
            return this.shrtNmField;
        }
        set {
            this.shrtNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum PartyType17Code {
    
    /// <remarks/>
    OTHN,
    
    /// <remarks/>
    OTHP,
    
    /// <remarks/>
    ACQR,
    
    /// <remarks/>
    ACQP,
    
    /// <remarks/>
    CISS,
    
    /// <remarks/>
    CISP,
    
    /// <remarks/>
    AGNT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:canm.002.001.03")]
public enum PartyType18Code {
    
    /// <remarks/>
    ACQR,
    
    /// <remarks/>
    CISS,
    
    /// <remarks/>
    CSCH,
    
    /// <remarks/>
    AGNT,
}
